BBBBBBB BBBBBBBBBBBBBBBB

BBBBB BBBBBFFFFFBBBBBBBB
BBBBB BBBBBBB
XXXXXXXX XXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXX

    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB

    XXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXX
      XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXX

          XXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX

            XXXX
              XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
              XX XXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX
              BB BBBBBBBBBBBBB BB BBB
              XX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX
              XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
              BBBB
              XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XX XXXXXXXXXXXXX
              BBBBB
            XXXXXX
            XXXXXXXXXXXXXXXXXX XXXXXXXX XXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXX

          XXXXXX
          XXXXX XXXXXXXXX

          XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX
            BBBBBBBBBB
            
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB

          XXXXXXX

        XXXXXX
      XXXXXX
    XXXXXX

  XXXXXX
XXXXXXXXXX


BBBBBBBB

BBBBB BB
    
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
  
BBBBBBBB