BBBBBBB BBBBBBBBBBBBBBBB


BBBBB BBBBB  BBBBBBBB
BBBBB BBBBBBB
XXXXXXXX XXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXX

    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB

    XXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXX
      XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXX

          XXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX

            XXXX
              XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX
            XXXXXXXXXXXXXXXXXX XXXXXXXX XXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXX

          XXXXXX
          XXXXX XXXXXXXXX

            XXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX
            BBBBBBBBBB
            XXXX XXXXXXX
            XXXX XXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXX

                BBB BBBBB BB BBBB
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXX
                      XXXXXXXXXXXXXXXBB BBBBBBBBBBBBBBBBBBBBXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXBBBBB
                      BB BBBBBBBBBBBBXXXXXX XXXXXXXXXXXXXXBBB BBBBB BB BBBBBBBBBBBBBBBBBBXXXXXXXXBBBBB
                      
                    XXXXXX
                  XXXXXX
                XXXXXX
                BBBBBB

              XXXXXX
              XXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
            XXXXXXXXXXXX
          XXXXXXX

        XXXXXX
      XXXXXX
    XXXXXX

  XXXXXX
XXXXXXXXXX


BBBBBBBB

BBBBB BB
    
  BBBB BBBBBB
  XXXX XXXXXX XX XXXXXX XXX
  XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX


XXXXXXXX

XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
    XXXXX X XXXXXXXXXXXXXXXXXXXXX
             XXXXXXXX XX XXXXX

               XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX X
                   XXXXXXXXXXXXXXXX XX XXX XX XXXXXXXXXXXXX XX XXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXX XXXXX
                   XXXXXX
                       XXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
                   X
               XXX



             XXXXXX
                  XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX X
                   XXXXXXXXXXXXXXXX XX XXX XX XXXXXXXXXXXXX XX XXX XX XXXXXXXXXXXXX XX XXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXX XXXXX
                   XXXXXX
                       XXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
                   X
               XXX
             X
XXX


XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX

             XXXXX X XXXXXXXXXXXXXXXXXXXXX
             XXXXXXXX XX XXXXX

               XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX X
                   XXXXXXXXXXXXXXXX XX XXX XX XXXXXXXXXXXXX XX XXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXX XXXXX
                   XXXXXX
                       XXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
                   X
               XXX



             XXXXXX
                  XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX X
                   XXXXXXXXXXXXXXXX XX XXX XX XXXXXXXXXXXXX XX XXX XX XXXXXXXXXXXXX XX XXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXX XXXXX
                   XXXXXX
                       XXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
                   X
               XXX
             X


        XX
XXXXXXXXX

BBBBBBBB