BBBBBBB BBBBBBBBBBBBBBBB

BBBBB BBBBBXXXXXX XXXXXXBBBBBBBB
BBBBB BBBBBBB
XXXXXXXX XXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXX
    XXXXXX
      
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB

    XXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXX
          XXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXX
          XXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXX
          XXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
           BBBBBBBBBB
           
           BBB BBBBB BB BBBB

           XXXX XXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXX
              
            XXXXXX
          XXXXXX
          
          BBBBBB

          XXXX XXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXX
                
              XXXXXX
              XX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
          XXXXXX

          XXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX
        
      XXXXXX

    XXXXXX
  XXXXXX
  
XXXXXX
XXXXXXXXXX


BBBBBBBB