BBBBBBB BBBBBBBBBBBBBBBB

BBBBB BBBBBXXXXXXXXBBBBBBBB
BBBBB BBBBBBB
XXXXXXXX XXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXX
    XXXXXX
    
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBB

    XXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXX
        XXXXX XXXXXXXXX XXXXXXXXXXXXXX
          BBBBBBBBBB
          XXXX XXXXXXXXXXXXXXX
            XXXX
              XXXXXXXX XXXXXXXXXXX
            XXXXX
              XXXX XXXXXXXXXXXXXXXXXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXX
          XXXXXX

          XXXX XXXXXXXXXXXXX

           BBBBBBB BBBBBBBBBBBBBBBBBB

           XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
              XXXXXXX
                XXXX
                  XXXXXXXXXXXX                   
                  XXXXXXXX XX XXXXXXXXXXXX
                  XXXXXXXXXXXXXX
                  XXXXXXXXXXXXX
                  XXXXXXXXXXXXXXXXXX
                  XXXXXXXXXXXXXXX
                  XXXXXXXXXXXXXXXX
                XXXXX
              XXXXXXXX

              XXXXXXX
               BB BBBBBBBBB
               BBB BBB BB BBBBBBBBB
               XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBXX
                XXXXXXXXX
                XXXXXXXXX
                XXXX
                    BB BBBBBBBBBBBBB
                            XXX
                        BBBB
                            XXX
                        BBBBB
                XXXXX
                XXXXFFFFFFFFFFFFFFFFFFXXXXX
                XXXXFFFFFFFFFFFFFFFFFFXXXXX
                XXXXBB BBBBBBBBBBBBBBBBXXXXXXXXXXXXXBBBBXXXXXXXBBBBBXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXX
                  BB BBB BBBBBBBBBBBBBBBB
                  XXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                  BBBBB
                XXXXX
              XXXXX
              BBBBBB
              BBBB
              BBBBB
            XXXXXXXX
          XXXXXXXX
        XXXXXX

      XXXXXX

    XXXXXXX

    BBBBBBB BBBBBBBBBBBBBBBBB

  XXXXXX
XXXXXX

XXXXXX
XXXXXXXXXX


BBBBBBBB