   XXXX XXXXXXXXXXXXXXXXX X
BBBBBBB BBBBBBBBBBBBBBBB


BBBBB BBBBBXXXXXBBBBBBBB
BBBBB BBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBXXXXXXXXXX XXXXXXXXXBBBBBBBB

BBBBB BBBBBBB

XXXX XXXXXXXXXXXXXXXXXX



	XXXX XXXXXXXXXXXXX XXXXXXX
  XXXX XXXXXXXXXXXXXX XXXXXXX



    BBBBBBB BBBBBBBBBBBBBBBBB

    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX

        XXXX XXXXXXXXXXXXX
        	BB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
            XXXXX XXXXXXXXXX XXXXXXXXXXXXXX
            	BBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXX XXX XXXX XX XXXXXXX X X XXXXX XXXX XXXXXX

                BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB

                XXXXXX

                BBB BBBBB BB BBBB
                XXXX XXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXX
                        
                    XXXXXX
                XXXXXX
                BBBBBB

                XXXX XXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                XXXXXX

                XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBXXXXXXXXXX X XXXXXXXXXXXXXXX
                    XXXXXXXXXXXX XXXX XXX XXXXXXXX XXXXXX XXXX X XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX

            XXXXXXX
            BBBBB

            BBBBBBB BBBBBBBBBBBBBBBBB

        XXXXXX
    XXXXXX
XXXXXX

BBBBBBBB


BBBBB BB

    XXXX XXXXXXXX XXXX XXXXXXX XX XXXXXXXXX XXXXX XX XXXXX XXX
    BB BBBBBBBB

    BBB BBBBBBB BB BBBBBBBB
    BB BBBBBBBBB BB BBBBBBBBBBBB

    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXX
    BBBBB
    BBBBBB

    BBBBB

BBBBBBBB

    XXXXXX