BBBBBBB BBBBBBBBBBBBBBBB

BBBBB BBBBBXXXXXXBBBBBBBB
BBBBB BBBBBBB
XXXXXXXX XXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXX
    XXXXXX
    
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBB

    XXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXX
          XXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXX
          XXXXX
          XXXX XXXXXXXXXXXXXXXXXXX
              XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX
              XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX
          XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXXXX
          XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX  
              BB BBBBBBBBBBBBBBBBB
              XXXX XXXXXXXXXXXXXXX
              BBBB
              XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              BBBBB
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXX
                XXXXXXX
                  XXXX
                    XXXXXXXXXXXXXXXX
                    XXXXBB BBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXBBBBXXXXXXXBBBBBXXXXX
                  XXXXX
                  XXXX
                    XXXXXXXXXXXXXX
                    XXXXXXXXX
                  XXXXX
                  XXXX
                    XXXXXXXXXXXXXXXXXXX
                    XXXXXXXXX
                  XXXXX
                  XXXX
                    XXXXXXXX XX XXXXXXXXXXXXX
                    XXXXXXXXX
                  XXXXX
                  XXXX
                    XXXXXXXXXXXXX
                    XXXXBB BBBBBBBBBBBBBBBBBBBBBBBB BB BBBXXXBBBBXXXBBBBBXXXXX
                  XXXXX
                  XXXX
                    XXXXXXXXXXXXXXX XXXXXXXXXXXXX
                    XXXXBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBXXXBBBBXXXBBBBBXXXXX
                  XXXXX
                   XXXX
                    XXXXXXXXXXXXXXXX
                    XXXXXXXXX
                  XXXXX
                  XXXX
                    XXXXXXXXXXXXXXX
                    XXXXXXXXX
                  XXXXX
                  XXXX
                    XXXXXXXXX XXXXXXXXXXXXX
                    XXXXXXXXX
                  XXXXX
                XXXXXXXX
              XXXXXXXX

            XXXXXX

          XXXXXX              
        XXXXXX
      XXXXXX
    XXXXXX

  XXXXXX
XXXXXXXXXX


BBBBBBBB