BBBBBBB BBBBBBBBBBBBBBBB

BBBBB BBBBBXXXXXXXXXX XXXXXXXBBBBBBBB

BBBBB BBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBB
	
	XXXX XXXXXXXXXXXXX
		XXXX XXXXXXXXXXXXXXX
			XXXXXXXXXXXXX XXX XXXXXXXXXXXX
		XXXXXX
		XXXX XXXXXXXXXXXXX
			XXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX
			BBBBBBBBBB
				BBB BBBBB BB BBBB
				XXXX XXXXXXXXXXXXXXXXXXX
					XXXXXXXXXXXXXXX
					BB BBBBBBBBBBBBXXXXXX XXXXXXXXXXXXXXBBB BBBBB BB BBBBBBBBBBBBBBBBBBXXXXXXXXBBBBB
					XXXX XXXXXXXXXXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXXXXX
			      			
			      		XXXXXX
			      		XX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		      		XXXXXX
		      	XXXXXX
		    	BBBBBB
		    	XXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
	    	XXXXXXX
    	XXXXXX
   	XXXXXX
	
BBBBBBBB

BBBBB BB
XXXXXXXX

	XXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXXXXXX
BBBBBBBB