version: '3.3'
services:
  web:
    build: ./
    command: gunicorn djangosige.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
    - .:/usr/src/app
    env_file:
      - ./.env

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web

  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    depends_on:
      - nginx
    command: >-
            certonly --reinstall --webroot --webroot-path=/var/www/certbot 
            --email jpramos@dpltech.com.br --agree-tos --no-eff-email
            -d norli.cloud 
    volumes:
      - ./etc/letsencrypt:/etc/letsencrypt
      - ./certbot/data:/var/www/certbot

volumes:
  postgres_data: