XXXX XXXXXXX
XXXX XXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXX
    
        BBB BBBBB BB BBBB
        XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXBB BBBBBBBBBBBBBBBBBBBBXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXBBBBB
              BB BBBBBBBBBBBBXXXXXX XXXXXXXXXXXXXXBBB BBBBB BB BBBBBBBBBBBBBBBBBBXXXXXXXXBBBBB
              
            XXXXXX
          XXXXXX
        XXXXXX
        BBBBBB

  XXXXXX

  XXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
XXXXXX
XXXXXXXXXXXX