BBBB BBBBBB
XXXX XXXXXX XXXX XXXXX XX XXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBXXXXXXXXXXX

BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB

BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB

BBBBBBB BBBBBBBBBBBBBBBBBBBBBB

 XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXX X XX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XBBB BBBBBBBBBBBBBBBBBBBBBBBBBX
    XXXXXXXXXXXXXXXXXXXXXXXXX X XBBB BBBBBBBBBBBBBBBBBBBBBBX
    XXXXXXXXXXXXXXXXXXXXXXXXXXX X XBBB BBBBBBBBBBBBBBBBBBBBBBBBBBX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXX