# Generated by Django 3.2.10 on 2023-08-07 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0005_auto_20230807_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='planocontasgrupo',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
