# Generated by Django 3.2.10 on 2023-08-08 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0006_planocontasgrupo_observacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='planocontasgrupo',
            name='codigo_legado',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
