# Generated by Django 3.2.10 on 2023-08-18 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0005_auto_20230818_1449'),
        ('financeiro', '0007_planocontasgrupo_codigo_legado'),
    ]

    operations = [
    ]
