

XXXX XXXXXXXXXXXXXXX XX
  XXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXX
      BB BBBBBBBBBBBBBBBBXXXXXX XXXXXXXXXXXXXXBBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBXXXXXXXXBBBBB
      
    XXXXXX
  XXXXXX
XXXXXX


XXXX XXXXXXXXXXXXXXX XX
  XXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXX
      BB BBBBBBBBBBBBBBBBBBBBXXXXXX XXXXXXXXXXXXXXBBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXBBBBB
      
    XXXXXX
  XXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXX XX
  XXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXX
      BB BBBBBBBBBBBBBBBBBXXXXXX XXXXXXXXXXXXXXBBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXBBBBB
      
    XXXXXX
  XXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXX XX
  XXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXX
      BB BBBBBBBBBBBBBBBXXXXXX XXXXXXXXXXXXXXBBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXBBBBB
      
    XXXXXX
  XXXXXX
XXXXXX



XXXX XXXXXXXXXXXXXXX XX
  XXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXX
      BB BBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXX XXXXXXXXXXXXXXBBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXBBBBB
      
    XXXXXX
  XXXXXX
XXXXXX

