XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
    XXXXXXX
      XXXX
        XXXXXXXXXXXX                   
        XXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX
        XXXXXXXXX XXXXXXXXXXXX
        XXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXX
      XXXXX
    XXXXXXXX

    XXXXXXX
     BB BBBBBBBBBBBBBBB
     BBB BBBBB BB BBBBBBBBBBBBBBB
     XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBXX
      XXXXXXXXX
      XXXXXXXXX
      XXXXFFFFFFFFFFFFFFFFFFXXXXX
      XXXXFFFFFFFFFFFFFFFFFFXXXXX
      XXXXFFFFFFFFFFFFFFFFFFXXXXX
      XXXXXXXXX
      XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX
    XXXXX
    BBBBBB
    BBBB
    BBBBB
  XXXXXXXX
XXXXXXXX
XXXXXX