BBBBBBB BBBBBBBBBBBBBBBB

BBBBB BBBBBFFFFFBBBBBBBB
BBBBB BBBBBBB
XXXXXXXX XXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX
  
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
    
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBB

    XXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXX
        XXXXX XXXXXXXXX XXXXXXXXXXXXXX
          BBBBBBBBBB
          XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX
              
            XXXXX
              XXXX XXXXXXXXXXXXXXXXXXX
                BB BBBBBBB
                XX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                BBBB
                XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                  XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                    XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXX X XXXXXXXXXXXXXX
                    XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXX X XXXXXXXXXXXXXXXX
                  XXXXX
                XXXXXX
                BBBBB
                XXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXX
          XXXXXX

          XXXX XXXXXXXXXXXXX

           BBBBBBB BBBBBBBBBBBBBBBBBB

           BB BBBBBBBBBBBBBBB
           BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
           BBBB BBBBBBBBBBBBBBBBB
           BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
           BBBB BBBBBBBBBB
           BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
           BBBB BBBBBBBBBBBB
           BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
           BBBB BBBBBBBBBBBBBBB
           BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
           BBBB
           XXXXXX XXXXXXXX XXXXXXXXXX
           BBBBB

      XXXXXX

    XXXXXXX

    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

  XXXXXX
XXXXXX

XXXXXX
XXXXXXXXXX


BBBBBBBB

BBBBB BB
  BBBB BBBBBB
  XXXX XXXXXX XXXX XXXXX XX XXX
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
  
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB

  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB

  BBBBBBB BBBBBBBBBBBBBBBBBBBBBB

  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXX X XX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXX
  
BBBBBBBB