XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
    XXXXXXX
      XXXX
        XXXXXXXXXXXX                   
        XXXXXXXXXXXXXXXXXX
        XXXXXXXX XX XXXXXXXXXXXXXX
        XXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXX
        XXXXXXXXX XXXXXXXXXXXX
        XXXXXXXXXXXXXXXX
      XXXXX
    XXXXXXXX

    XXXXXXX
     BB BBBBBBBBBB
     BBB BBBBB BB BBBBBBBBBB
     XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBXX
      XXXXXXXXX
      XXXXXXXXX
      XXXXFFFFFFFFFFFFFFFFFFXXXXX
      XXXXFFFFFFFFFFFFFFFFFFXXXXX
      XXXXFFFFFFFFFFFFFFFFFFXXXXX
      XXXXXXXXX
      XXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX
    XXXXX
    BBBBBB
    BBBB
    BBBBB
  XXXXXXXX
XXXXXXXX
XXXXXX