XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
    XXXXXXX
      XXXX
        XXXXXXXXXXXX                   
        XXXXXXXXXXXXXXXXXX
        XXXXXXXX XX XXXXXXXXXXXXXX
        XXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXX
        XXXXXXXXX XXXXXXXXXXXX
        XXXXXXXXXXXXXXXX
      XXXXX
    XXXXXXXX

    XXXXXXX
     BB BBBBBBBBBBBB
     BBB BBBBBBB BB BBBBBBBBBBBB
     XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBXX
      XXXXXXXXX
      XXXXXXXXX
      XXXXFFFFFFFFFFFFFFFFFFXXXXX
      XXXXFFFFFFFFFFFFFFFFFFXXXXX
      XXXXFFFFFFFFFFFFFFFFFFXXXXX
      XXXXXXXXX
      XXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX
    XXXXX
    BBBBBB
    BBBB
    BBBBB
  XXXXXXXX
XXXXXXXX
XXXXXX