XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
    XXXXXXX
      XXXX
        XXXXXXXXXXXX                   
        XXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXX
        XXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXX XXXXXXXXXXXX
        XXXXXXXXXXXXXXXX
      XXXXX
    XXXXXXXX

    XXXXXXX
     BB BBBBBBBBBBBBBBB
     BBB BBBBBBBBBB BB BBBBBBBBBBBBBBB
     XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
      XXXXXXXXX
      XXXXXXXXX
      XXXXXXXXX
      XXXXFFFFFFFFFFFFFFFFFFXXXXX
      XXXXBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXX
      XXXXBB BBBBBBBBBBBBBBBBBBBBBBXXXXX
      XXXXBB BBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBXXXXX
      XXXXXXXXX
      XXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX
    XXXXX
    BBBBBB
    BBBB
    BBBBB
  XXXXXXXX
XXXXXXXX
XXXXXX