# Generated by Django 3.2.10 on 2022-11-19 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_exemplo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exemplo',
        ),
    ]
