# Generated by Django 3.2.10 on 2023-06-20 20:01

from django.db import migrations, models
import django.db.models.deletion
import django_cpf_cnpj.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0007_auto_20230614_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minhaempresa',
            name='m_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='minha_empresa', to='cadastro.empresa'),
        ),
        migrations.AlterField(
            model_name='pessoajuridica',
            name='cnpj',
            field=django_cpf_cnpj.fields.CNPJField(max_length=18, null=True, unique=True),
        ),
    ]
