# Generated by Django 3.2.10 on 2023-08-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0011_alter_pessoafisica_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='codigo_legado',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
