# Generated by Django 3.2.10 on 2023-07-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0011_alter_pessoafisica_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartamentoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
    ]
