# Generated by Django 3.2.10 on 2023-07-20 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_remove_usuario_departamento'),
        ('cadastro', '0012_departamentomodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DepartamentoModel',
        ),
    ]
