# Generated by Django 3.2.10 on 2023-08-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0014_departamentomodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='codigo_legado',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
