# Generated by Django 3.2.10 on 2023-08-18 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0012_produto_codigo_legado'),
        ('cadastro', '0015_produto_codigo_legado'),
    ]

    operations = [
    ]
