BBBBBBB BBBBBBBBBBBBBBBB

BBBBB BBBBBFFFFFBBBBBBBB
BBBBB BBBBBBB
XXXXXXXX XXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXX

    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB

    XXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXX
      XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXX

          XXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX

            XXXX
              XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
              XX XXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX
              BB BBBBBBBBBBBBB BB BBB
              XX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX
              XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
              BBBB
              XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XX XXXXXXXXXXXXX
              BBBBB
            XXXXXX
            XXXXXXXXXXXXXXXXXX XXXXXXXX XXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXX

          XXXXXX
          XXXXX XXXXXXXXX

          XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX
            BBBBBBBBBB
            
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB

          XXXXXXX

        XXXXXX
      XXXXXX
    XXXXXX

  XXXXXX
XXXXXXXXXX


BBBBBBBB

BBBBB BB
    
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB 
  
BBBBBBBB