XXX XXXXXXXXXXXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXX XX XXXXXXXXXXXX
BBBBBBB BBBBBBBBBBBBBBBBBB

 XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
  XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
    XXXXXXX
      XXXX
        XXXXXXXXXXXX
        XXXXXXXXXXXXX                   
        XXXXXXXXXXXXXXX
        XXXXXXXX XX XXXXXXXXXXXXXXX
        XXXXXXXXXXXXXX
      XXXXX
    XXXXXXXX

    XXXXXXX
     BBB BBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
     XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XXXXXXXXX
        XXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXX
        XXXXBB  BBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXX
        XXXXXXXXX        
      XXXXX
      BBBBBB
    XXXXXXXX
  XXXXXXXX
XXXXXX