BBBBBBB BBBBBBBBBBBBBBBB

BBBBB BBBBBXXXXXBBBBBBBB
BBBBB BBBBBBB
XXXXXXXX XXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX
  
    XXXX XXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXX
    XXXXXX
    
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBB

    XXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXX
        XXXXX XXXXXXXXX XXXXXXXXXXXXXX
          BBBBBBBBBB
          XXXX XXXXXXXXXXXXXXX
            XXXX
              XXXXXX XXXXXXXXXXX
            XXXXX
              XXXX XXXXXXXXXXXXXXXXXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXX
          XXXXXX

          XXXX XXXXXXXXXXXXX

           BBBBBBB BBBBBBBBBBBBBBBBBB

           XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
              XXXXXXX
                XXXX
                  XXXXXXXXXXXX                   
                  XXXXXXXXXXXXXXXXXX
                  XXXXXXXXXXXXXXXX
                XXXXX
              XXXXXXXX

              XXXXXXX
               BB BBBBBBBBBB
               BBB BBBBB BB BBBBBBBBBB
               XXX XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBXX
                XXXXXXXXX
                XXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXX
                  XXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX
              XXXXX
              BBBBBB
              BBBB
              BBBBB
            XXXXXXXX
          XXXXXXXX
        XXXXXX

      XXXXXX

    XXXXXXX

  XXXXXX
XXXXXX

XXXXXX
XXXXXXXXXX


BBBBBBBB