
XXXX XXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
    
    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXXXX XXX XXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXX
  XXXXXX

  XXXX XXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXX
        BB BBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXX XXXXXXXXXXXXXXBBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXBBBBB
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXX

  XXXX XXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXX XX XXXXXXX XXXXXXXXXXXXX
      XXXXX  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBB BBBBBBBBBBBBBBBBBBBBBBBBXXXXBBBBBXXXXXXX
    XXXXXX
  XXXXXX

  BB BBB BBBBBB
  XXXX XXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXX XXXXXXXXXXXX XX XXXXXXX XXXXXXX XXXX XXXX XXXXXXXX X XXXXXXXXXXXX XXXXXX XXX XXXXXXXXXXX XX XXXXXX XX XXXXXXX X XXXXXXXXXXXXX XX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXX
        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXX XXXXXXXXXXXXXXBBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXBBBBB
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXX

   XXXX XXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXX
        BB BBBBBBBBBBBBBBBBBBBBBBXXXXXX XXXXXXXXXXXXXXBBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXBBBBB
        XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXX
          XXXX XXXXXXXXXXXXXXXXXX
            
          XXXXXX
          XX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
      XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXX
        BB BBBBBBBBBBBBBBBBBBBBBBXXXXXX XXXXXXXXXXXXXXBBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXBBBBB
        XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXX
          XXXX XXXXXXXXXXXXXXXXXX
            
          XXXXXX
          XX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XX XXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
  BBBBB

XXXXXX