XXXX XXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXX
      BB BBBBBBBBBBBBBBBXXXXXX XXXXXXXXXXXXXXBBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXBBBBB
      
    XXXXXX
  XXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX
      BB BBBBBBBBBBBBBBBBBBXXXXXX XXXXXXXXXXXXXXBBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXBBBBB
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
      
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXX
      BB BBBBBBBBBBBBBBBBXXXXXX XXXXXXXXXXXXXXBBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBXXXXXXXXBBBBB
      
    XXXXXX
  XXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX
  	XXXXXXXXXXXXXXX
    BB BBBBBBBBBBBBBBBBBBBBBBBXXXXXX XXXXXXXXXXXXXXBBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXBBBBB
    XXXX XXXXXXXXXXXXXXXXXXXX
	    XXXX XXXXXXXXXXXXXXXXXX
	      
	    XXXXXX
	    XX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX
  XXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX
  	XXXXXXXXXXXXXXX
    BB BBBBBBBBBBBBBBBBBBBBBBBBXXXXXX XXXXXXXXXXXXXXBBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXBBBBB
    XXXX XXXXXXXXXXXXXXXXXXXX
	    XXXX XXXXXXXXXXXXXXXXXX
	      
	    XXXXXX
	    XX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX
  XXXXXX
XXXXXX