BBBB BBBBBB
XXXX XXXXXX XXXX XXXXX XX XXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBXXXXXXXXXXX

XXXX XXXXXXXX XXXXXXXXXXXX XXX
XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX

BBBBBBB BBBBBBBBBBBBBBBBBBBBBB

XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXX X XBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBX
    XXX XXXXXXXXX X XBBBBBB BBBBBBBBBBBBBBBBBBBBBBBX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXXXXXX