XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
    XXXXXXX
      XXXX
        XXXXXXXXXXXX
        XXXXXXXXXXXXXX XXXXXXXXXXX
        XXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXX
      XXXXX
    XXXXXXXX

    XXXXXXX
      BB BBBBBBBBBBBBBBBBBBB
      BBB BBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBB
      XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBXX
        XXXXXXXXX
        XXXXXXXXX
        XXXXBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB BBBBFFFFFFFFFFFFFFFFFFBBBBFFFFFFFFFFFFFFFFFFBBBBBBBBBBXXXXX
        XXXXBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXX
        XXXXFFFFFFFFFFFFFFFFFFXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX
      XXXXX
      BBBBBB
      BBBB
      BBBBB
    XXXXXXXX
  XXXXXXXX
XXXXXX