BBBBB BB
    
  BBBB BBBBBB
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
  	XXX XXXXXXXXX X XBBBBBB BBBBBBBBBBBBBBBBBBBBBX

  	XXX XXXXXXXXXXX X XXX
  	BBB BBBB BB BBBBBBBBBBBBB
  	XXXXXXXXXXXXXXXXXXXXX
  	BBBBBB

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
  XXXXXXXXX  
  
BBBBBBBB