XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
    XXXXXXX
      XXXX
        XXXXXXXXXXXX                   
        XXXXXXXXXXXXXX XXXXXXXXXXX
        XXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXX
      XXXXX
    XXXXXXXX

    XXXXXXX
      BB BBBBBBBBBBBB
      BBB BBBBBBB BB BBBBBBBBBBBB
      XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBXX
        XXXXXXXXX
        XXXXXXXXX
        XXXXFFFFFFFFFFFFFFFFFFXXXXX
        XXXXBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXX
        XXXXFFFFFFFFFFFFFFFFFFXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX
      XXXXX
      BBBBBB
      BBBB
      BBBBB
    XXXXXXXX
  XXXXXXXX
XXXXXX