XXXX XXXXX XXXXXXXX XXXXXXX XXX XXXX XXXXXXXXXX XX XXXX XXX
XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    BBBBBBBBBB

      XXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
          XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXX XXXXXX BB BBBBBBB XX XXXXXXXXXXBBBBBXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXX

            XXXX XXXXXXXXXX XXXXXXX XXX XXX
            XXXX XXXXXXXXXXXX
              XXX XXXXXXXXXXXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXX X XXXXXXX XX XXXX XXXXXXXXXXX
            XXXXXX
            
            XXXX XXXXXXXXXXXX

              XXXX XXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXX XXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
                  XXXXXX
                XXXXXX
              XXXXXX

              BB BBBBB
              XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
              BBBB BBBBBBB
              XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
              BBBBB

            XXXXXX
            XXXX XXXXXXXXXXX XXXXXXX XXX XXX

          XXXXXX

        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
          XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
      XXXXXX
    XXXXXXX
  XXXXXX
XXXXXX
XXXX XXXX