BBBBBBB BBBBBBBBBBBBBBBB

BBBBB BBBBBFFFFFBBBBBBBB
BBBBB BBBBBBB
XXXXXXXX XXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX

    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
    
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBB
    BBBBBBB BBBBBBBBBBBBBBBBBBBBB

    XXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXX
        XXXXX XXXXXXXXX XXXXXXXXXXXXXX
          BBBBBBBBBB
          XXXX XXXXXXXXXXXXXXX
            XXXX
              
            XXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
              BB BBBBB
              XX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX
              BBBBB
              XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
              XXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
          XXXXXX

          XXXX XXXXXXXXXXXXX

           BBBBBBB BBBBBBBBBBBBBBBBBB

           XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
              XXXXXXX
                XXXX
                  XXXXXXXXXXXX
                  XXXXXXXXXXXXX
                  XXXXXXXXXXXXXXXXXXXXX
                  XXXXXXXX XX XXXXXXXXXXXX
                  BB BBBBB
                  XXXXXXXXXXXXXXXX
                  BBBB BBBBBBB
                  XXXXXXXXXXXXXXXXXXX
                  BBBBB
                  XXXXXXXXXXXXXXX
                  XXXXXXXXXXXXXXXX
                XXXXX
              XXXXXXXX

              XXXXXXX
               BB BBBBBBBBB
               BBB BBBB BB BBBBBBBBB
               BB BBBBB
               XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBXX
               BBBB BBBBBBB
               XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBXX
               BBBBB
                XXXXXXXXX
                XXXXXXXXX
                XXXXXBB BBBBBBBBB BBBBBBBBBBBBXXXXX
                XXXXFFFFFFFFFFFFFFFFFFXXXXX
                XXXXBB BBBBBBBBB BBBBBBBBBBBBXXXXX
                XXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXX
                  XXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX
              XXXXX
              BBBBBB
              BBBB
              BBBBB
            XXXXXXXX
          XXXXXXXX
        XXXXXX

      XXXXXX

    XXXXXXX

    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  XXXXXX
XXXXXX

XXXXXX
XXXXXXXXXX


BBBBBBBB

BBBBB BB
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB

  BBBBBBB BBBBBBBBBBBBBBBBBBBBBB
    
   XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        BB BBBBBBB
        XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXX XX XXXXXXXXXXX XXXXXXXXXXXXX
        BBBB BBBBB
        XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXXXX
        BBBBB
    XXX
  XXXXXXXXX
  
BBBBBBBB