BBBBBBB BBBBBBBBBBBBBBBB

BBBBB BBBBBFFFFFBBBBBBBB
BBBBB BBBBBBB
XXXXXXXX XXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXX

    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB

    XXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXX
      XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXX
          BBBBBBB BBBBBBBBBBBBBBBBBBBBB
          XXXBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBXXXX
          XXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX

            XXXX
              XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX 
            XXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
              BB BBBBB
              XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                  XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBXXXXXXXXX XXXXXXXXXXXX
                  XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBXXXXXXXX XXXXXXXXXXXXX
                  XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBXXXXXXXXXXX XXXXXXXXXXXXX
                  XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBXXXXXXXX XXXXXXXXXXXXX
                  XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBXXXXXXXXXX XXXXXXXXXXXXX
                  XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBXXXXXXXX XXXXXXXXXXXXX
                  BB BBBBBBBBBB BB BBBB
                  XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBXXXXXXX XXXXXXXXXXXXXX
                  BBBB BBBBBBBBBB BB BBBB
                  XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBXXXXXXX XXXXXXXXXXXXXXX
                  BBBBB
                XXXXX
              XXXXXX
              BBBBB
            XXXXXX
            XXXXXXXXXXXXXXXXXX XXXXXXXX XXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXX

          XXXXXX
          XXXXX XXXXXXXXX

          XXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            BBBBBBBBBB
            
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

          XXXXXXX

          BB BBBBB
          BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
          BBBB BBBBBBB
          BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
          BBBBB

        XXXXXX
      XXXXXX
    XXXXXX

  XXXXXX
XXXXXXXXXX


BBBBBBBB

BBBBB BB
    
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  
BBBBBBBB