XXXX XXXXXXX
XXXX XXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXX
    XXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX
      XXXX XXX XXXXX XXX
      XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX

        BBB BBBBB BB BBBB
        XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXBB BBBBBBBBBBBBBBBBBBBBXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXBBBBB
              BB BBBBBBBBBBBBXXXXXX XXXXXXXXXXXXXXBBB BBBBB BB BBBBBBBBBBBBBBBBBBXXXXXXXXBBBBB
              
            XXXXXX
          XXXXXX
        XXXXXX
        BBBBBB
      XXXXXX
      XXXX XXXX XXXXX XXX

      XXXX XXX XXXXX XXX
        XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXX XXX XXXXXX XXXXXXXX X XXXXXX XX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXX
          BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
          XXXXXX
        XXXXXX

      XXXXXX
      
  XXXXXX

  XXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
XXXXXX
XXXXXXXXXXXX