BBBBBBB BBBBBBBBBBBBBBBB

BBBBB BBBBBFFFFFBBBBBBBB
BBBBB BBBBBBB
XXXXXXXX XXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX

    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB

    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBB



    XXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXX
        XXXXX XXXXXXXXX XXXXXXXXXXXXXX
          BBBBBBBBBB
          XXXX XXXXXXXXXXXXXXX
            XXXX
              
            XXXXX
              XXXX XXXXXXXXXXXXXXXXXXX

              XXXXXX
          XXXXXX

          XXXX XXXXXXXXXXXXX
XXXXXXXXXXXXXXXXX
          XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
           BBBBBBB BBBBBBBBBBBBBBBBBB

           XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
              XXXXXXX
                XXXX
                    XXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXX
                    XXXXXXXXXXXX
                    XXXXXXXXXXXX
                    XXXXXXXXXXXX
                    XXXXXXXXXXXX
                    XXXXXXXXXXXX
                    XXXXXXXXXXXX
                    XXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXX XXXXXXXXXX
                    XXXXXXXXXXXX XXXXXXXXXX


                XXXXX
              XXXXXXXX

              XXXXXXX
               BB BBBBBBBBBB
               BBB BBBBB BB BBBBBBBBBB
                 XXXX
                   XXXXXXXXX
                   XXXXXXXXX
                   XXXXXXXXX
                   XXXXXXXXX
                   XXXXXXXXX
                   XXXXXXXXX
                   XXXXXXXXX
                   XXXXXXXXX
                   XXXXXXXXX
                   XXXXXXXXX
                   XXXXXXXXX
                   XXXXXXXXX
                   XXXXXXXXX
                   XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXX
                   XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXX

              XXXXX
              BBBBBB
              BBBB
              BBBBB
            XXXXXXXX
          XXXXXXXX
        XXXXXX

      XXXXXX

    XXXXXXX

  XXXXXX
XXXXXX

XXXXXX
XXXXXXXXXX


BBBBBBBB