BBBBBBB BBBBBBBBBBBBBBBB

BBBBB BBBBBFFFFFBBBBBBBB
BBBBB BBBBBBB
XXXXXXXX XXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX

    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB

    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBB

    XXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXX
        XXXXX XXXXXXXXX XXXXXXXXXXXXXX
          BBBBBBBBBB
          XXXX XXXXXXXXXXXXXXX
            XXXX
              
            XXXXX
              XXXX XXXXXXXXXXXXXXXXXXX
                  XX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX
                  XXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXX
          XXXXXX

          XXXX XXXXXXXXXXXXX

           BBBBBBB BBBBBBBBBBBBBBBBBB

           XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
              XXXXXXX
                XXXX
                    XXXXXXXXXXXX
                    XXXXXXXXXXXX
                    XXXXXXXXXXXX
                    XXXXXXXXXXXX
                    XXXXXXXXXXXX
                    XXXXXXXXXXXX
                    XXXXXXXXXXXX
                    XXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXX

                XXXXX
              XXXXXXXX

              XXXXXXX
               BB BBBBBBBBBB
               BBB BBBBB BB BBBBBBBBBB
                 XXXX
                   XXXXXXXXX
                   XXXXXXXXX
                   XXXXXXXXX
                   XXXXXXXXX
                   XXXXXXXXX
                   XXXXXXXXX
                   XXXXXXXXX
                   XXXXXXXXX
                   XXXXXXXXX
                   XXXX
                    BB BBBBBBBBBBBBBB BB B
                        XX XXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXX
                    BBBBB
                     BB BBBBBBBBBBBBBB BB B
                        XX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                    BBBBB
                    BB BBBBBBBBBBBBBB BB B
                        XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    BBBBB
                   BB BBBBBBBBBBBBBB BB B
                        XX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                    BBBBB
                   XXXXX

               XXX XXXXXXXXXXXXXXXXXXXXX

                    BB BBBBBBBBBBBBBB BB B
                        XXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    BBBBB


                XXXXX
              XXXXX
              BBBBBB
              BBBB
              BBBBB
            XXXXXXXX
          XXXXXXXX
        XXXXXX

      XXXXXX

    XXXXXXX

  XXXXXX
XXXXXX

XXXXXX
XXXXXXXXXX


BBBBBBBB