BBBBBBB BBBBBBBBBBBBBBBB

BBBBB BBBBBFFFFFBBBBBBBB
BBBBB BBBBBBB
XXXXXXXX XXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX

    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB

    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBB

    XXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXX
        XXXXX XXXXXXXXX XXXXXXXXXXXXXX
          BBBBBBBBBB
          XXXX XXXXXXXXXXXXXXX
            XXXX
              
            XXXXX
              XXXXX
                  XXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXX
          XXXXXX

          XXXX XXXXXXXXXXXXX

           BBBBBBB BBBBBBBBBBBBBBBBBB

           XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
              XXXXXXX
                XXXX
                    XXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXX
                    XXXXXXXXXXXX
                    XXXXXXXXXXXX
                    XXXXXXXXXXXX
                    XXXXXXXXXXXX
                    XXXXXXXXXXXX
                    XXXXXXXXXXXX
                    XXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXX

                XXXXX
              XXXXXXXX

              XXXXXXX
               BB BBBBBBBBBB
               BBB BBBBB BB BBBBBBBBBB
                 XXXX
                   XXXXXXXXX
                   XXXXXXXXX
                   XXXXXXXXX
                   XXXXXXXXX
                   XXXXXXXXX
                   XXXXXXXXX
                   XXXXXXXXX
                   XXXXXXXXX
                   XXXXXXXXX
                   XXXXXXXXX


               XXX XXXXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX
              XXXXX
              BBBBBB
              BBBB
              BBBBB
            XXXXXXXX
          XXXXXXXX
        XXXXXX

      XXXXXX

    XXXXXXX

  XXXXXX
XXXXXX

XXXXXX
XXXXXXXXXX


BBBBBBBB