BBBBBBB BBBBBBBBBBBBBBBB

BBBBB BBBBBXXXXXX XXXXXXBBBBBBBB
BBBBB BBBBBBB
XXXXXXXX XXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXX
    XXXXXX
      
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB

    XXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXX
          XXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXX
          XXXXX
        XXXXXX
      BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

        XXXX XXXXXXXXXXXXX
          XXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
              BBBBBBBBBB
              XXXX XXXXXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                      BBB BBBBB BB BBBB

                        XXXX XXXXXXXXXXXXXXXXX
                           XXXX XXXXXXXXXXXXXXXXXXX
                               XXXX XXXXXXXXXXXXXXXXXX
                                    XXXXXXXXXXXXXXX
                                    
                               XXXXXX
                            XXXXXX
                        XXXXXX

                      BBBBBB

         XXXXXX

                    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                         BBBBBBB BBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBB BBBBBBBBBB
                    XXXXXX


                    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                         BBBBBBB BBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBB


                    XXXXXX

                        XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXX
                                XXXXXXXXXXXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXXX
                                XXXX XXXXXXXXXXXXXXXXXX
                                    
                                XXXXXX
                                XX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXX
                        XXXXXX
                    XXXXXX
        
      XXXXXX
           XXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
   XXXXXXX
        XXXXXX
    XXXXXX
  XXXXXX
  
XXXXXX
XXXXXXXXXX


BBBBBBBB

BBBBB BB

  BBBB BBBBBB
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
  	XXX XXXXXXXXX X XBBBBBB BBBBBBBBBBBBBBBBBBBBBX

  	XXX XXXXXXXXXXX X XXX
  	BBB BBBB BB BBBBBBBBBBBBB
  	XXXXXXXXXXXXXXXXXXXXX
  	BBBBBB

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
  XXXXXXXXX

BBBBBBBB