BBBBBBB BBBBBBBBBBBBBBBB


BBBBB BBBBB  BBBBBBBB
BBBBB BBBBBBB

XXXXXXX
XXXXXXXXX
    XXXXXX XXXXXX
    XXXXXXX XXXXXX
X
XXXXXXXXXX
    XXXXXX XXXXX
    XXXXXXXXXXXX XXXXX
    XXXXXXXXXXX XXXXX
X
XXXXXXXXX XXXXXX
    XXXXXXXXXXXXX XXXXX
    XXXXXX XXXXX
X

XXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXX
    XXXXXXX XXXXXX
    XXXXXXXXXXXXXX XXXX
    XXXXXXXXXXXX XXXXX
    XXXXXXXXXXX XXXXX
    XXXXXX XXXXX
X
XXXXXXXX

XXXXXXXX XXXXXXXXXXXXXXXX

  XXXX XXXXXXXXXXXXXXXXXXXXXXXX

    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB

    XXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXX
      XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXX

          XXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX

            XXXX
              XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX
            XXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
            XXXXX

          XXXXXX
          XXXXX XXXXXXXXX
                XXXX XXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXX
                                XXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXXXXXXXXXXXXXXXXXX   XXXX
                                XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX
                            XXXXXX
                XXXXXX
          XXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            BBBBBBBBBB
            XXXX XXXXXXX
            XXXX XXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXX
                  XXXX XXXXXXXXXXXXXXXXXXXX

                        XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX  XXXXXXXXXXXXXXXXXXXX
                            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
                             BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                             BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                        XXXXXX
                      XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

                      XXXXXX
                  XXXXXX
              XXXXXX
              XXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
          XXXXXXX
          
        XXXXXX
      XXXXXX
    XXXXXX

  XXXXXX
XXXXXXXXXX


BBBBBBBB

BBBBB BB
    
  BBBB BBBBBB
  XXXX XXXXXX XX XXXXXX XXX
  XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX

  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXX X XBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    
  XXXXXXXXX
  
BBBBBBBB