# Generated by Django 3.2.10 on 2023-08-11 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpiniaoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(choices=[('1', 'Dúvida'), ('2', 'Sugestão/Opinião'), ('3', 'Elogio'), ('4', 'Crítica'), ('5', 'Reportar um problema')], default='2', max_length=1)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('opiniao', models.CharField(max_length=500)),
                ('rating', models.IntegerField(blank=True, default=0)),
                ('anexo', models.FileField(blank=True, null=True, upload_to='files/')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opiniao_opiniao_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Opiniões',
                'permissions': (('analisar_opinioes', 'Vizualiza todas as opiniões'),),
            },
        ),
    ]
