# Generated by Django 3.2.10 on 2023-08-16 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opiniao', '0002_alter_opiniaomodel_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OpiniaoModel',
        ),
    ]
