# Generated by Django 3.2.10 on 2023-04-13 15:21

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0006_delete_exemplo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=50)),
            ],
            options={
                'verbose_name': 'Controle de Projeto',
                'permissions': (('controle_projeto', 'Pode controlar projetos'),),
            },
        ),
        migrations.CreateModel(
            name='FilialModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=50)),
                ('cnpj', models.CharField(default='', max_length=50)),
                ('endereco', models.CharField(default='', max_length=200)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filial_empresa', to='cadastro.empresa')),
            ],
            options={
                'verbose_name': 'Controle de Projeto',
                'permissions': (('controle_projeto', 'Pode controlar projetos'),),
            },
        ),
        migrations.CreateModel(
            name='ExemploModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='projeto', max_length=50)),
                ('parcelas', models.IntegerField(blank=True, null=True)),
                ('valor_proposta', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('desconto', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('valor_final', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_projeto', to='cadastro.cliente')),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filial_projeto', to='norli_projeto.filialmodel')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_projeto', to='norli_projeto.tipomodel')),
            ],
            options={
                'verbose_name': 'Controle de Projeto',
                'permissions': (('controle_projeto', 'Pode controlar projetos'),),
            },
        ),
    ]
