# Generated by Django 3.2.10 on 2023-04-17 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norli_projeto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exemplomodel',
            name='desconto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exemplomodel',
            name='valor_final',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exemplomodel',
            name='valor_proposta',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
