# Generated by Django 3.2.10 on 2023-08-10 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('norli_projeto', '0003_alter_filialmodel_empresa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exemplomodel',
            options={'ordering': ['nome'], 'permissions': (('controle_projeto', 'Pode controlar projetos'),), 'verbose_name': 'Controle de Projeto'},
        ),
    ]
