XXXX XXXXXXXXXXXXXXXXXXXX

  BBB BBBB BB BBBBBBB
  XXXX XXXXXX XXXXXXXXXXXXXXXX

    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXX XXXXX XXXXXXXXXX XX XXXXXXXXXXXXX XX XXXXX XXXXXXXX XXXXXXX XX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX

    BBB BBBBB BB BBBBBBBBBBBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXX
          BB BBBBBBBBBBBBXXXXXX XXXXXXXXXXXXXXBBB BBBBB BB BBBBBBBBBBBBBBBBBBXXXXXXXXBBBBB
          
        XXXXXX
      XXXXXX
    XXXXXX
    BBBBBB

    

    XXXX XXXXXXXXXXXXXXXXXX
      XX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
    XXXXXX
  XXXXXX

  BBBBBB

  

XXXXXX