XXXX XXXXXXXXXXXXXXXXXXXX

  BBB BBBB BB BBBBBBB
  XXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX

    XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX
      XXXXXXX
        XXXX
          BBB BBBBB BB BBBBBBBBBBBBBBBBBBB
          XXXXBB BBBBBBBBBBBBXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXBBB BBBBB BB BBBBBBBBBBBBBBBBBBXXXXXXXXBBBBBXXXXX      
          BBBBBB
          XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX
      XXXXXXXX

      XXXXXXX
       XXXX
          BBB BBBBB BB BBBBBBBBBBBBBBBBBBB
          XXX XXXXXXXXXXXXXXXXXXXXXX
          BBBBBB
          XXXXXXXXX
        XXXXX
      XXXXXXXX
    XXXXXXXX

    

    XXXX XXXXXXXXXXXXXXXXXX
      XX XXXXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX
    XXXXXX
  XXXXXX

  BBBBBB

  

XXXXXX