# Generated by Django 3.2.10 on 2023-06-20 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0008_auto_20230620_1701'),
        ('fiscal', '0004_auto_20221115_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notafiscalentrada',
            name='dest_entrada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dest_nfe_entrada', to='cadastro.empresa'),
        ),
        migrations.AlterField(
            model_name='notafiscalsaida',
            name='emit_saida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emit_nfe_saida', to='cadastro.empresa'),
        ),
    ]
