# Generated by Django 3.2.10 on 2023-08-07 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0015_produto_codigo_legado'),
        ('fiscal', '0005_auto_20230620_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notafiscal',
            name='versao',
            field=models.CharField(choices=[('4.00', 'v4.00')], default='4.00', max_length=4),
        ),
        migrations.AlterField(
            model_name='notafiscalentrada',
            name='dest_entrada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dest_nfe_entrada', to='cadastro.empresa'),
        ),
        migrations.AlterField(
            model_name='notafiscalsaida',
            name='emit_saida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emit_nfe_saida', to='cadastro.empresa'),
        ),
    ]
