# Generated by Django 3.2.10 on 2023-08-16 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0005_auto_20230620_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notafiscal',
            name='inf_cpl',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
