# Generated by Django 3.2.10 on 2023-08-16 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0006_alter_notafiscal_inf_cpl'),
        ('fiscal', '0006_auto_20230807_1330'),
    ]

    operations = [
    ]
