BBBBBBB BBBBBBBBBBBBBBBB

BBBBB BBBBBFFFFFBBBBBBBB
BBBBB BBBBBBB
XXXXXXXX XXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXX

    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB

    XXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXX
      XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXX

          XXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX

            XXXX
              XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX
            XXXXXXXXXXXXXXXXXX XXXXXXXX XXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXX

          XXXXXX
          XXXXX XXXXXXXXX

          XXXXX XXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX
            BBBBBBBBBB
            XXXX XXXXXXX
            XXXX XXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXX

                BBB BBBBB BB BBBB
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXX

                      XXXXXXXXXXXXXXXBB BBBBBBBBBBBBBBBBBBBBXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXBBBBB
                      BB BBBBBBBBBBBBXXXXXX XXXXXXXXXXXXXXBBB BBBBB BB BBBBBBBBBBBBBBBBBBXXXXXXXXBBBBB
                      
                    XXXXXX
                  XXXXXX
                XXXXXX
                BBBBBB

              XXXXXX
                XXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXX
                XXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
            XXXXXXXXXXXX
          XXXXXXX

        XXXXXX
      XXXXXX
    XXXXXX

  XXXXXX
XXXXXXXXXX


BBBBBBBB

BBBBB BB

  BBBB BBBBBB
  XXXX XXXXXX XX XXXXXX XXX
  XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX

  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXX X XBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

  XXXXXXXXX

BBBBBBBB