# Generated by Django 3.2.10 on 2023-07-20 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_auto_20221115_1505'),
        ('compras', '0003_auto_20221115_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='plano_conta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compra_plano_conta', to='financeiro.planocontasgrupo'),
        ),
    ]
