BBBBBBB BBBBBBBBBBBBBBBB

BBBBB BBBBBFFFFFBBBBBBBB
BBBBB BBBBBBB
XXXXXXXX XXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX
  
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
    
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBB

    XXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXX
        XXXXX XXXXXXXXX XXXXXXXXXXXXXX
          BBBBBBBBBB
          XXXX XXXXXXXXXXXXXXX
            XXXX
              
            XXXXX
              XXXX XXXXXXXXXXXXXXXXXXX
                XX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXX
          XXXXXX

          XXXX XXXXXXXXXXXXX

           BBBBBBB BBBBBBBBBBBBBBBBBB

           XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
              XXXXXXX
                XXXX
                    XXXXXXXXXXX XXXXXXXX
                    XXXXXXXXXXXX XXXXXXXX
                    XXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXX
                XXXXX
              XXXXXXXX

              XXXXXXX
               BB BBBBBBBBBB
               BBB BBBBB BB BBBBBBBBBB
               XXX X
                    XXXXXXXXX
                    XXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXX
              XXXXX
              BBBBBB
              BBBB
              BBBBB
            XXXXXXXX
          XXXXXXXX
        XXXXXX

      XXXXXX

    XXXXXXX

  XXXXXX
XXXXXX

XXXXXX
XXXXXXXXXX


BBBBBBBB