BB BBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX
    XXXXXX
  XXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXXX
BBBB
XXXX XXXXXXXXXXXXXXXXX
BBBBB
  XXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXX
      BB BBBBBBBBBBBBBBBBBBBBBBBBBXXXXXX XXXXXXXXXXXXXXBBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXBBBBB
      
    XXXXXX
  XXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX
      BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXX XXXXXXXXXXXXXXBBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXBBBBB
      
    XXXXXX
  XXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXX
  XXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXX
        XXXXX
        XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX   XXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XX XXXXXXX XXXX XXXXXX
XXXX          XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXX XXXXXXXXXXXX
        XXXXXXXXX
      XXXXXX
    XXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXXXXX
      XXXXX
      XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBB BB BBBB XXXXXXXXXXXXXXXXXBBBBBXX
      XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXX
  XXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX
      BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXX XXXXXXXXXXXXXXBBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXBBBBB
      
    XXXXXX
  XXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXX
      BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXX XXXXXXXXXXXXXXBBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXBBBBB
      
    XXXXXX
  XXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXX
      BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXX XXXXXXXXXXXXXXBBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXBBBBB
      
    XXXXXX
  XXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXX
      BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXX XXXXXXXXXXXXXXBBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXBBBBB
      
    XXXXXX
  XXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXX
      BB BBBBBBBBBBBBBBBBXXXXXX XXXXXXXXXXXXXXBBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBXXXXXXXXBBBBB
      
    XXXXXX
  XXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXX
      BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXX XXXXXXXXXXXXXXBBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXBBBBB
      
    XXXXXX
  XXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXX
      BB BBBBBBBBBBBBBBBBXXXXXX XXXXXXXXXXXXXXBBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBXXXXXXXXBBBBB
      
    XXXXXX
  XXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXX
      BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXX XXXXXXXXXXXXXXBBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXBBBBB
      
    XXXXXX
  XXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXX
      BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXX XXXXXXXXXXXXXXBBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXBBBBB
      
    XXXXXX
  XXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXX
      BB BBBBBBBBBBBBBBBBBBBBBBBBBXXXXXX XXXXXXXXXXXXXXBBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXBBBBB
      
    XXXXXX
  XXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXX
      BB BBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXX XXXXXXXXXXXXXXBBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXBBBBB
      
    XXXXXX
  XXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXX
      BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXX XXXXXXXXXXXXXXBBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXBBBBB
      
    XXXXXX
  XXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXX
      BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXX XXXXXXXXXXXXXXBBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXBBBBB
      
    XXXXXX
  XXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXX
      BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXX XXXXXXXXXXXXXXBBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXBBBBB
      
    XXXXXX
  XXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXX
      BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXX XXXXXXXXXXXXXXBBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXBBBBB
      
    XXXXXX
  XXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXX
      BB BBBBBBBBBBBBBBBBBBBBBBBBXXXXXX XXXXXXXXXXXXXXBBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXBBBBB
      
    XXXXXX
  XXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXX
      BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXX XXXXXXXXXXXXXXBBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXBBBBB
      
    XXXXXX
  XXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXX
      BB BBBBBBBBBBBBBBBBBBBBBXXXXXX XXXXXXXXXXXXXXBBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXBBBBB
      
    XXXXXX
  XXXXXX
XXXXXX