BBBBB BB
    
  BBBB BBBBBB
  XXXX XXXXXX XXXX XXXXX XX XXX
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBXXXXXXXXXXX

  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB

  BBBBBBB BBBBBBBBBBBBBBBBBBBBBB

  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXX
  
BBBBBBBB