# Generated by Django 3.2.10 on 2023-06-14 12:06

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPassagemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HorarioPreferencialModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MoedaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MotivoDeViagemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeDespesaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=10)),
                ('descricao', models.CharField(max_length=300)),
                ('nome', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeTransporteModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TiposDeSolicitacaoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TiposDeViagemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TiposNecessidadeEspecialModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ViagemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inclusao', models.DateTimeField(auto_now_add=True)),
                ('valor_passagem', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('itinerario', models.CharField(choices=[('0', 'Ida'), ('1', 'Ida e Volta')], max_length=2)),
                ('escalas', models.CharField(choices=[('0', 'Direto'), ('1', '1 escala'), ('2', '2+ escalas')], max_length=1)),
                ('dada_inicio', models.DateTimeField()),
                ('dada_fim', models.DateField(blank=True, null=True)),
                ('origem', models.CharField(max_length=200)),
                ('destino', models.CharField(max_length=200)),
                ('objetivo', models.TextField(max_length=512)),
                ('justificativa', models.TextField(blank=True, max_length=512)),
                ('autorizada', models.BooleanField(default=False)),
                ('homologada', models.BooleanField(default=False)),
                ('pagamento', models.CharField(blank=True, choices=[('RECURSOS DA EMPRESA', 'RECURSOS DA EMPRESA'), ('RECURSOS PRÓPRIOS', 'RECURSOS PRÓPRIOS')], max_length=50, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('dada_inicio_realizada', models.DateTimeField(blank=True, null=True)),
                ('dada_fim_realizada', models.DateField(blank=True, null=True)),
                ('remarcacao_interesse_particular', models.CharField(choices=[('1', 'SIM'), ('0', 'NAO')], default=0, max_length=50)),
                ('finalizar_pc', models.CharField(blank=True, choices=[('1', 'SIM'), ('0', 'NAO')], default='0', max_length=50, null=True)),
                ('aprovar_pc', models.CharField(blank=True, choices=[('2', 'REPROVADO'), ('1', 'APROVADO'), ('0', 'EM ANÁLISE')], default='0', max_length=50, null=True)),
                ('bagagem_tecnica', models.BooleanField(blank=True, default=False)),
                ('bagagem_despachada', models.BooleanField(blank=True, default=False)),
                ('crianca_colo', models.BooleanField(blank=True, default=False)),
                ('local_risco', models.BooleanField(blank=True, default=False)),
                ('exige_vacina', models.BooleanField(blank=True, default=False)),
                ('reservar_hotel', models.BooleanField(blank=True, default=False)),
                ('alimentacao_terceiros', models.BooleanField(blank=True, default=False)),
                ('acompanhante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viagem_acompanhante', to=settings.AUTH_USER_MODEL)),
                ('categoria_passagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viagem_passagem', to='viagem.categoriapassagemmodel')),
                ('horario_preferencial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viagem_horario', to='viagem.horariopreferencialmodel')),
                ('motivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viagem_motivo', to='viagem.motivodeviagemmodel')),
                ('necessidade_especial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viagem_necessidade_especial', to='viagem.tiposnecessidadeespecialmodel')),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viagem_user', to=settings.AUTH_USER_MODEL)),
                ('tipo_solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viagem_solicitacao', to='viagem.tiposdesolicitacaomodel')),
                ('tipo_transporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viagem_transporte', to='viagem.tipodetransportemodel')),
                ('tipo_viagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viagem_tipo', to='viagem.tiposdeviagemmodel')),
            ],
            options={
                'verbose_name': 'Viagens',
                'permissions': (('solicitar_viagens', 'Pode solicitar viagens'), ('autorizar_viagens', 'Pode autorizar viagens'), ('homologar_viagens', 'Pode homologar viagens'), ('cadastrar_item_viagens', 'Cadastrar Items de Viagem')),
            },
        ),
        migrations.CreateModel(
            name='Arquivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('file', models.FileField(upload_to='files/')),
                ('viagem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arquivos_viagem', to='viagem.viagemmodel')),
            ],
        ),
    ]
