# Generated by Django 3.2.10 on 2023-06-26 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viagem', '0002_auto_20230620_1658'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viagemmodel',
            options={'permissions': (('solicitar_viagens', 'Pode solicitar viagens'), ('autorizar_viagens_sup', 'Pode autorizar viagens - Superintendente'), ('autorizar_viagens_dus', 'Pode autorizar viagens - Diretor de Unidade de Serviço'), ('homologar_viagens', 'Pode homologar viagens'), ('cadastrar_item_viagens', 'Cadastrar Items de Viagem'), ('aprovar_pc_viagens', 'Aprovar prestação de contras de Viagem')), 'verbose_name': 'Viagens'},
        ),
    ]
