# Generated by Django 3.2.10 on 2023-07-12 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viagem', '0004_auto_20230701_1120'),
        ('viagem', '0004_auto_20230704_1846'),
    ]

    operations = [
    ]
