# Generated by Django 3.2.10 on 2023-08-07 16:32

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_usuario_departamento'),
        ('viagem', '0005_auto_20230802_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDePagamentoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='viagemmodel',
            options={'permissions': (('solicitar_viagens', 'Pode solicitar viagens'), ('autorizar_viagens_sup', 'Pode autorizar viagens - Superintendente'), ('autorizar_viagens_dus', 'Pode autorizar viagens - Diretor de Unidade de Serviço'), ('homologar_viagens', 'Pode homologar viagens'), ('cadastrar_item_viagens', 'Cadastrar Items de Viagem'), ('aprovar_pc_viagens', 'Aprovar prestação de contras de Viagem'), ('autorizar_pagamento_diarias', 'Pode autorizar pagamento de diárias'), ('autorizar_pagamento_reembolso', 'Pode autorizar pagamento de reembolso')), 'verbose_name': 'Viagens'},
        ),
        migrations.AddField(
            model_name='trechomodel',
            name='categoria_passagem_trecho',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='viagem_trecho_passagem', to='viagem.categoriapassagemmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viagemmodel',
            name='homologada_reembolso',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='viagemmodel',
            name='tem_reembolso',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trechomodel',
            name='data_fim_trecho',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AprovarPagamentoReembolsoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(blank=True, max_length=3, null=True)),
                ('agencia', models.CharField(blank=True, max_length=8, null=True)),
                ('conta', models.CharField(blank=True, max_length=32, null=True)),
                ('digito', models.CharField(blank=True, max_length=8, null=True)),
                ('total_recursos_proprios', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_recursos_empresa', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('valor_total_reembolso', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('data_autorizacao', models.DateTimeField(blank=True, null=True)),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.usuario')),
                ('tipo_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='viagem.tipodepagamentomodel')),
                ('viagem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='viagem.viagemmodel')),
            ],
        ),
        migrations.CreateModel(
            name='AprovarPagamentoDiariasModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(blank=True, max_length=3, null=True)),
                ('agencia', models.CharField(blank=True, max_length=8, null=True)),
                ('conta', models.CharField(blank=True, max_length=32, null=True)),
                ('digito', models.CharField(blank=True, max_length=8, null=True)),
                ('qtd_diarias', models.FloatField(blank=True, null=True)),
                ('valor_diaria', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('valor_total_diarias', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('data_autorizacao', models.DateTimeField(blank=True, null=True)),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.usuario')),
                ('tipo_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='viagem.tipodepagamentomodel')),
                ('viagem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='viagem.viagemmodel')),
            ],
        ),
    ]
