# Generated by Django 3.2.10 on 2023-08-07 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viagem', '0006_auto_20230807_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viagemmodel',
            name='categoria_passagem',
        ),
        migrations.RemoveField(
            model_name='viagemmodel',
            name='destino',
        ),
        migrations.RemoveField(
            model_name='viagemmodel',
            name='localidade_destino',
        ),
        migrations.RemoveField(
            model_name='viagemmodel',
            name='motivo',
        ),
        migrations.RemoveField(
            model_name='viagemmodel',
            name='origem',
        ),
        migrations.RemoveField(
            model_name='viagemmodel',
            name='tipo_transporte',
        ),
        migrations.AddField(
            model_name='trechomodel',
            name='localidade_trecho',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='viagem_trecho_localidade_destino', to='viagem.localidademodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trechomodel',
            name='motivo_trecho',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='viagem_trecho_motivo', to='viagem.motivodeviagemmodel'),
            preserve_default=False,
        ),
    ]
