# Generated by Django 3.2.10 on 2023-08-14 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viagem', '0008_auto_20230807_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trechomodel',
            name='localidade_trecho',
        ),
        migrations.AddField(
            model_name='viagemmodel',
            name='localidade_destino',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='viagem_localidade_destino', to='viagem.localidademodel'),
            preserve_default=False,
        ),
    ]
