# Generated by Django 3.2.10 on 2023-08-16 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagem', '0009_auto_20230814_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriapassagemmodel',
            name='descricao',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='horariopreferencialmodel',
            name='descricao',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='localidademodel',
            name='descricao',
            field=models.CharField(max_length=400, unique=True),
        ),
        migrations.AlterField(
            model_name='moedamodel',
            name='descricao',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='motivodeviagemmodel',
            name='nome',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='tipodedespesamodel',
            name='descricao',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='tipodedespesamodel',
            name='nome',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='tipodedespesamodel',
            name='sigla',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='tipodepagamentomodel',
            name='nome',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='tipodetransportemodel',
            name='nome',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='tiposdesolicitacaomodel',
            name='nome',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='tiposdeviagemmodel',
            name='nome',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='tiposnecessidadeespecialmodel',
            name='descricao',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AddConstraint(
            model_name='tabeladiariamodel',
            constraint=models.UniqueConstraint(fields=('grupo_funcional', 'localidade_destino'), name='Grupo funcional e localidade'),
        ),
    ]
