# Generated by Django 3.2.10 on 2023-08-16 17:51

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_usuario_departamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viagem', '0009_auto_20230814_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalViagemModel',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('data_inclusao', models.DateTimeField(blank=True, editable=False)),
                ('valor_passagem', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('itinerario', models.CharField(choices=[('0', 'Ida'), ('1', 'Ida e Volta'), ('2', 'Em trânsito')], max_length=2)),
                ('escalas', models.CharField(choices=[('0', 'Direto'), ('1', '1 escala'), ('2', '2+ escalas')], max_length=1)),
                ('duracao', models.CharField(choices=[('0', 'Inferior a 6hs'), ('1', 'Igual/Superior a 6hs')], max_length=1)),
                ('dada_inicio', models.DateTimeField()),
                ('dada_fim', models.DateTimeField(blank=True, null=True)),
                ('objetivo', models.TextField(max_length=512)),
                ('justificativa', models.TextField(blank=True, max_length=512)),
                ('autorizada_sup', models.BooleanField(default=False)),
                ('recusado_sup', models.BooleanField(default=False)),
                ('autorizada_dus', models.BooleanField(default=False)),
                ('recusado_dus', models.BooleanField(default=False)),
                ('homologada', models.BooleanField(default=False)),
                ('homologada_reembolso', models.BooleanField(default=False)),
                ('tem_reembolso', models.BooleanField(default=False)),
                ('pagamento', models.CharField(blank=True, choices=[('RECURSOS DA EMPRESA', 'Recursos da Empresa'), ('RECURSOS PRÓPRIOS', 'Recursos Próprios')], max_length=50, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('dada_inicio_realizada', models.DateTimeField(blank=True, null=True)),
                ('dada_fim_realizada', models.DateField(blank=True, null=True)),
                ('remarcacao_interesse_particular', models.CharField(choices=[('1', 'SIM'), ('0', 'NAO')], default=0, max_length=50)),
                ('finalizar_pc', models.CharField(blank=True, choices=[('1', 'SIM'), ('0', 'NAO')], default='0', max_length=50, null=True)),
                ('aprovar_pc', models.CharField(blank=True, choices=[('2', 'REPROVADO'), ('1', 'APROVADO'), ('0', 'EM ANÁLISE')], default='0', max_length=50, null=True)),
                ('motivo_reprovacao_pc', models.TextField(blank=True, max_length=512, null=True)),
                ('bagagem_tecnica', models.BooleanField(blank=True, default=False)),
                ('bagagem_despachada', models.BooleanField(blank=True, default=False)),
                ('local_risco', models.BooleanField(blank=True, default=False)),
                ('exige_vacina', models.BooleanField(blank=True, default=False)),
                ('reservar_hotel', models.BooleanField(blank=True, default=False)),
                ('alimentacao_terceiros', models.BooleanField(blank=True, default=False)),
                ('qtd_diarias', models.FloatField(blank=True)),
                ('valor_diaria', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('valor_total_diarias', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('justificativa_cancelamento', models.TextField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('acompanhante', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'grupo_funcional': '0'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='login.usuario')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('horario_preferencial', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='viagem.horariopreferencialmodel')),
                ('localidade_destino', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='viagem.localidademodel')),
                ('necessidade_especial', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='viagem.tiposnecessidadeespecialmodel')),
                ('solicitante', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tipo_solicitacao', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='viagem.tiposdesolicitacaomodel')),
                ('tipo_viagem', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='viagem.tiposdeviagemmodel')),
            ],
            options={
                'verbose_name': 'historical Viagens',
                'verbose_name_plural': 'historical Viagenss',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
