# Generated by Django 3.2.10 on 2023-08-18 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viagem', '0010_auto_20230818_1618'),
        ('viagem', '0010_historicalviagemmodel'),
    ]

    operations = [
    ]
