# Generated by Django 3.2.10 on 2023-08-18 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viagem', '0011_merge_20230818_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipodedespesamodel',
            name='nome',
        ),
        migrations.AddField(
            model_name='historicalviagemmodel',
            name='motivo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='viagem.motivodeviagemmodel'),
        ),
        migrations.AddField(
            model_name='tiposdesolicitacaomodel',
            name='dias_antecedencia',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='viagemmodel',
            name='motivo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='viagem_motivo', to='viagem.motivodeviagemmodel'),
            preserve_default=False,
        ),
    ]
