BBBBBBB BBBBBBBBBBBBBBBB

BBBBB BBBBBFFFFFBBBBBBBB
BBBBB BBBBBBB
XXXXXXXX XXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXX

    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB

    XXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXX
      XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXX

          XXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX

            XXXX
              XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX
            XXXXXXXXXXXXXXXXXX XXXXXXXX XXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXX

          XXXXXX
          XXXXX XXXXXXXXX

          XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX
            BBBBBBBBBB
            
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB

          XXXXXXX

        XXXXXX
      XXXXXX
    XXXXXX

  XXXXXX
XXXXXXXXXX


BBBBBBBB

BBBBB BB
    
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB 
  
BBBBBBBB