BBBBBBB BBBBBBBBBBBBBBBB

BBBBB BBBBBFFFFFBBBBBBBB
BBBBB BBBBBBB
XXXXXXXX XXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXX

    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB

    XXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXX
      XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXX

          XXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX

            XXXX
              XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
              XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XX XXXXXXXXXX
              XX XXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX
              BB BBBBBBBBBBBBB BB BBB
              XX XXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
              XX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
              BBBB BBBBBBBBBBBBB BB BBB
              XX XXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
              BBBBB
            XXXXXX
            XXXXXXXXXXXXXXXXXX XXXXXXXX XXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXX

          XXXXXX
          XXXXX XXXXXXXXX

          XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX
            BBBBBBBBBB
            
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB

          XXXXXXX

        XXXXXX
      XXXXXX
    XXXXXX

  XXXXXX
XXXXXXXXXX


BBBBBBBB

BBBBB BB
    
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  
BBBBBBBB