BBBB BBBBBB
XXXX XXXXXX XXXX XXXXX XX XXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBXXXXXXXXXXX

BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB

BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB

BBBBBBB BBBBBBBBBBBBBBBBBBBBBB

 XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXX X XX
    XXXXXXXXXXXXXXXXXXXXXXXXX X XBBB BBBBBBBBBBBBBBBBBBBBBBX
    XXXXXXXXXXXXXXXXXXXXXXX X XBBB BBBBBBBBBBBBBBBBBBX
    XXXXXXXXXXXXXXXXXXXXXXXX X XBBB BBBBBBBBBBBBBBBBBBBBX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    
  XXXXXXXXX