XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
    XXXXXXX
      XXXX
        XXXXXXXXXXXX                   
        XXXXXXXXXXXXX
        XXXXXXXXXXXXX
        XXXXXX XX XXXXXXXXXX
        XXXXXXXXX XXXXXXXXXX
        XXXXXXXXXXXXXXXX
      XXXXX
    XXXXXXXX

    XXXXXXX
     BB BBBBBBBBBB
     BBB BBBBB BB BBBBBBBBBB
     XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
      XXXXXXXXX
      XXXXXXXXX
      XXXXXXXXX
      XXXXXXXXX
      XXXXXXXXX
      XXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX
    XXXXX
    BBBBBB
    BBBB
    BBBBB
  XXXXXXXX
XXXXXXXX
XXXXXX