# Generated by Django 3.2.10 on 2023-01-17 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CVModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('telefone', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('cpf', models.CharField(blank=True, max_length=200, null=True)),
                ('inf_adicionais', models.CharField(blank=True, max_length=1055, null=True)),
                ('cargo', models.CharField(blank=True, max_length=200, null=True)),
                ('nome_cv_executivo', models.CharField(blank=True, max_length=200, null=True)),
                ('cv_executivo', models.CharField(blank=True, max_length=1055, null=True)),
                ('nome_cv_padrao', models.CharField(blank=True, max_length=200, null=True)),
                ('telefone_cv_padrao', models.CharField(blank=True, max_length=200, null=True)),
                ('endereco_cv_padrao', models.CharField(blank=True, max_length=200, null=True)),
                ('email_cv_padrao', models.CharField(blank=True, max_length=200, null=True)),
                ('perfil_cv_padrao', models.CharField(blank=True, max_length=1055, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='imagens/users')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cv_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CertificadoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='files/users')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificados_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
