BBBBBBB BBBBBBBBBBBBBBBB


BBBBB BBBBB  BBBBBBBB
BBBBB BBBBBBB
XXXXXXXX XXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXX

    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB

    XXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXX
      XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXX

          XXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX

            XXXX
              XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX
            XXXXXXXXXXXXXXXXXX XXXXXXXX XXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXX

          XXXXXX
          XXXXX XXXXXXXXX

          XXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX
            BBBBBBBBBB
            
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

          XXXXXXX
          
        XXXXXX
      XXXXXX
    XXXXXX

  XXXXXX
XXXXXXXXXX


BBBBBBBB

BBBBB BB
    
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  
BBBBBBBB