# Generated by Django 3.2.10 on 2023-07-20 20:24

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_auto_20221115_1505'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastro', '0013_delete_departamentomodel'),
        ('janela_unica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentomodel',
            name='data_inclusao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentomodel',
            name='dono',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dono_doc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentomodel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/users'),
        ),
        migrations.CreateModel(
            name='TramitacaoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documento_tramitacao', to='janela_unica.documentomodel')),
                ('user_enviado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_enviado', to=settings.AUTH_USER_MODEL)),
                ('user_recebido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_recebido', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoUnicoFinanceiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='janela_unica/documentos')),
                ('situacao', django_fsm.FSMField(choices=[('Edição Responsável', 'Edição Responsável'), ('Aguardando avaliação', 'Aguardando avaliação'), ('Aprovado Gerência', 'Aprovado Gerência'), ('Aprovado Superintendencia', 'Aprovado Superintendencia'), ('Aprovado Diretoria', 'Aprovado Diretoria'), ('Aprovado Análise Fiscal', 'Aprovado Análise Fiscal'), ('Aprovado Análise Financeira', 'Aprovado Análise Financeira'), ('Reprovado', 'Reprovado'), ('Finalizado', 'Finalizado')], default='Edição Responsável', max_length=50, protected=True, verbose_name='Avaliação')),
                ('data_inclusao', models.DateTimeField(auto_now_add=True)),
                ('tipo_arquivo', models.CharField(blank=True, choices=[('0', 'Nota Fiscal (NF-e)'), ('1', 'Boleto'), ('2', 'Comprovante de Pagamento'), ('3', 'Outros')], max_length=1, null=True)),
                ('numero', models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('chave', models.CharField(max_length=44)),
                ('mod', models.CharField(blank=True, choices=[('55', 'NF-e (55)'), ('65', 'NFC-e (65)')], max_length=2, null=True)),
                ('serie', models.CharField(blank=True, max_length=3, null=True)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('rateio', models.BooleanField(blank=True, null=True)),
                ('observacoes', models.CharField(blank=True, max_length=1055, null=True)),
                ('aprovado_gerencia', models.BooleanField(blank=True, null=True)),
                ('observacao_gerencia', models.CharField(blank=True, max_length=1055, null=True)),
                ('aprovado_superintendencia', models.BooleanField(blank=True, null=True)),
                ('observacao_superintendencia', models.CharField(blank=True, max_length=1055, null=True)),
                ('aprovado_diretoria', models.BooleanField(blank=True, null=True)),
                ('observacao_diretoria', models.CharField(blank=True, max_length=1055, null=True)),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fornecedor_documento_unico', to='cadastro.fornecedor')),
                ('plano_conta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nfe_entrada_analise_plano_conta', to='financeiro.planocontasgrupo')),
            ],
            options={
                'verbose_name': 'Documento Único Financeiro Entrada',
            },
        ),
    ]
