# Generated by Django 3.2.10 on 2023-07-14 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('janela_unica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentomodel',
            name='data_inclusao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentomodel',
            name='dono',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dono_doc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentomodel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/users'),
        ),
        migrations.CreateModel(
            name='TramitacaoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documento_tramitacao', to='janela_unica.documentomodel')),
                ('user_enviado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_enviado', to=settings.AUTH_USER_MODEL)),
                ('user_recebido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_recebido', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
