# Generated by Django 3.2.10 on 2023-07-24 00:34

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('janela_unica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentounicofinanceiro',
            name='cfop',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='documentounicofinanceiro',
            name='data_emissao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentounicofinanceiro',
            name='situacao',
            field=django_fsm.FSMField(choices=[('Edição Responsável', 'Edição Responsável'), ('Aguardando avaliação Gerência', 'Aguardando avaliação Gerência'), ('Aguardando avaliação Superintendencia', 'Aguardando avaliação Superintendencia'), ('Aguardando avaliação Diretoria', 'Aguardando avaliação Diretoria'), ('Aguardando Análise Fiscal', 'Aguardando Análise Fiscal'), ('Aguardando Análise Financeira', 'Aguardando Análise Financeira'), ('Reprovado', 'Reprovado'), ('Finalizado', 'Finalizado'), ('Cancelado', 'Cancelado'), ('Aprovado', 'Aprovado')], default='Edição Responsável', max_length=50, protected=True, verbose_name='Situação'),
        ),
    ]
