# Generated by Django 3.2.10 on 2023-07-23 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0013_delete_departamentomodel'),
        ('janela_unica', '0002_auto_20230723_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentounicofinanceiro',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pessoa_documento_unico', to='cadastro.pessoa'),
        ),
    ]
