# Generated by Django 3.2.10 on 2023-07-22 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('janela_unica', '0002_auto_20230720_1724'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentounicofinanceiro',
            options={'verbose_name': 'Documento Janela Única'},
        ),
        migrations.AddField(
            model_name='documentounicofinanceiro',
            name='aprovado_analise_financeira',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentounicofinanceiro',
            name='aprovado_analise_fiscal',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentounicofinanceiro',
            name='descricao',
            field=models.CharField(blank=True, max_length=1055, null=True),
        ),
        migrations.AddField(
            model_name='documentounicofinanceiro',
            name='observacao_analise_financeira',
            field=models.CharField(blank=True, max_length=1055, null=True),
        ),
        migrations.AddField(
            model_name='documentounicofinanceiro',
            name='observacao_analise_fiscal',
            field=models.CharField(blank=True, max_length=1055, null=True),
        ),
        migrations.AddField(
            model_name='documentounicofinanceiro',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsavel_documento_unico', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documentounicofinanceiro',
            name='situacao',
            field=django_fsm.FSMField(choices=[('Edição Responsável', 'Edição Responsável'), ('Aguardando avaliação Gerência', 'Aguardando avaliação Gerência'), ('Aguardando avaliação Superintendencia', 'Aguardando avaliação Superintendencia'), ('Aguardando avaliação Diretoria', 'Aguardando avaliação Diretoria'), ('Aguardando Análise Fiscal', 'Aguardando Análise Fiscal'), ('Aguardando Análise Financeira', 'Aguardando Análise Financeira'), ('Reprovado', 'Reprovado'), ('Finalizado', 'Finalizado')], default='Edição Responsável', max_length=50, protected=True, verbose_name='Situação'),
        ),
    ]
