# Generated by Django 3.2.10 on 2023-07-23 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('janela_unica', '0003_alter_documentounicofinanceiro_fornecedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentounicofinanceiro',
            name='antecipacao_pagamento',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentounicofinanceiro',
            name='data_lancamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentounicofinanceiro',
            name='extra_orcamentaria',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentounicofinanceiro',
            name='numero_lancamento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='documentounicofinanceiro',
            name='observacao_pagamento',
            field=models.CharField(blank=True, max_length=1055, null=True),
        ),
        migrations.AddField(
            model_name='documentounicofinanceiro',
            name='pagamento_boleto',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentounicofinanceiro',
            name='pagamento_realizado',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentounicofinanceiro',
            name='possui_parcelamento',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentounicofinanceiro',
            name='usuario_analise_financeira',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documento_unico_usuario_analise_financeira', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentounicofinanceiro',
            name='usuario_analise_fiscal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documento_unico_usuario_analise_fiscal', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentounicofinanceiro',
            name='usuario_diretoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documento_unico_usuario_diretoria', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentounicofinanceiro',
            name='usuario_gerencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documento_unico_usuario_gerencia', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentounicofinanceiro',
            name='usuario_lancamento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='documentounicofinanceiro',
            name='usuario_superintendencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documento_unico_usuario_superintendencia', to=settings.AUTH_USER_MODEL),
        ),
    ]
