# Generated by Django 3.2.10 on 2023-07-25 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('janela_unica', '0003_auto_20230725_0723'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentounicofinanceiro',
            options={'permissions': (('gerencia_documento_unico', 'Aprovar documentos janela única - Gerência'), ('superintendencia_documento_unico', 'Aprovar documentos janela única - Superintendencia'), ('diretoria_documento_unico', 'Aprovar documentos janela única - Diretoria'), ('analise_fiscal_documento_unico', 'Aprovar documentos analise fiscal - Fiscal'), ('analise_financeira_documento_unico', 'Aprovar documentos analise financeira - Financeiro')), 'verbose_name': 'Documento Janela Única'},
        ),
    ]
