# Generated by Django 3.2.10 on 2023-07-25 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('janela_unica', '0003_auto_20230725_0723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentounicofinanceiro',
            name='comprovante_lancamento',
        ),
        migrations.RemoveField(
            model_name='documentounicofinanceiro',
            name='comprovante_pagamento',
        ),
    ]
