# Generated by Django 3.2.10 on 2023-07-23 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('janela_unica', '0004_auto_20230723_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentounicofinanceiro',
            old_name='usuario_superintendencia',
            new_name='usuario_superintencencia',
        ),
    ]
