# Generated by Django 3.2.10 on 2023-07-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janela_unica', '0006_historicaldocumentounicofinanceiro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaldocumentounicofinanceiro',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
    ]
