# Generated by Django 3.2.10 on 2023-08-07 16:30

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('janela_unica', '0007_alter_historicaldocumentounicofinanceiro_history_change_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentounicofinanceiro',
            name='chave_pix',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='documentounicofinanceiro',
            name='forma_pagamento',
            field=models.CharField(choices=[('0', 'Boleto'), ('1', 'TED'), ('2', 'PIX'), ('9', 'Outros')], default='9', max_length=1),
        ),
        migrations.AddField(
            model_name='documentounicofinanceiro',
            name='linha_digitavel',
            field=models.CharField(blank=True, max_length=48, null=True),
        ),
        migrations.AddField(
            model_name='documentounicofinanceiro',
            name='valor_liquido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='documentounicofinanceiro',
            name='valor_retencao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='historicaldocumentounicofinanceiro',
            name='chave_pix',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicaldocumentounicofinanceiro',
            name='forma_pagamento',
            field=models.CharField(choices=[('0', 'Boleto'), ('1', 'TED'), ('2', 'PIX'), ('9', 'Outros')], default='9', max_length=1),
        ),
        migrations.AddField(
            model_name='historicaldocumentounicofinanceiro',
            name='linha_digitavel',
            field=models.CharField(blank=True, max_length=48, null=True),
        ),
        migrations.AddField(
            model_name='historicaldocumentounicofinanceiro',
            name='valor_liquido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='historicaldocumentounicofinanceiro',
            name='valor_retencao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='documentounicofinanceiro',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, max_digits=13, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='historicaldocumentounicofinanceiro',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, max_digits=13, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.CreateModel(
            name='ArquivoDocumentoUnico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='janela_unica/documentos')),
                ('data_inclusao', models.DateTimeField(auto_now_add=True)),
                ('documento_unico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documento_unico_arquivo', to='janela_unica.documentounicofinanceiro')),
            ],
            options={
                'verbose_name': 'Arquivo do Documento Unico',
                'verbose_name_plural': 'Arquivos do Documento Unico',
            },
        ),
    ]
