# Generated by Django 3.2.10 on 2023-07-26 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('janela_unica', '0004_auto_20230725_1009'),
        ('janela_unica', '0007_alter_historicaldocumentounicofinanceiro_history_change_reason'),
    ]

    operations = [
    ]
