# Generated by Django 3.2.10 on 2023-08-14 16:53

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('janela_unica', '0009_auto_20230809_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoContrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Tipo de Contrato',
                'verbose_name_plural': 'Tipos de Contratos',
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='janela_unica/contratos')),
                ('data_inclusao', models.DateTimeField(auto_now_add=True)),
                ('data_validade', models.DateTimeField(blank=True, null=True)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('situacao', django_fsm.FSMField(choices=[('Rascunho', 'Rascunho'), ('Em Execução', 'Em Execução'), ('Finalizado', 'Finalizado'), ('Cancelado', 'Cancelado')], default='Rascunho', max_length=50, protected=True, verbose_name='Situação')),
                ('tipo_contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tipo_contrato', to='janela_unica.tipocontrato')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
            },
        ),
    ]
