# Generated by Django 3.2.10 on 2023-08-18 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cadastro', '0016_merge_20230818_1651'),
        ('janela_unica', '0010_contrato_tipocontrato'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPagamentoContrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Forma de Pagamento',
            },
        ),
        migrations.RemoveField(
            model_name='documentounicofinanceiro',
            name='agencia',
        ),
        migrations.RemoveField(
            model_name='documentounicofinanceiro',
            name='banco',
        ),
        migrations.RemoveField(
            model_name='documentounicofinanceiro',
            name='cfop',
        ),
        migrations.RemoveField(
            model_name='documentounicofinanceiro',
            name='chave',
        ),
        migrations.RemoveField(
            model_name='documentounicofinanceiro',
            name='chave_pix',
        ),
        migrations.RemoveField(
            model_name='documentounicofinanceiro',
            name='cnpj',
        ),
        migrations.RemoveField(
            model_name='documentounicofinanceiro',
            name='conta',
        ),
        migrations.RemoveField(
            model_name='documentounicofinanceiro',
            name='digito',
        ),
        migrations.RemoveField(
            model_name='documentounicofinanceiro',
            name='linha_digitavel',
        ),
        migrations.RemoveField(
            model_name='documentounicofinanceiro',
            name='mod',
        ),
        migrations.RemoveField(
            model_name='documentounicofinanceiro',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='documentounicofinanceiro',
            name='serie',
        ),
        migrations.RemoveField(
            model_name='documentounicofinanceiro',
            name='tipo_anexo',
        ),
        migrations.RemoveField(
            model_name='historicaldocumentounicofinanceiro',
            name='agencia',
        ),
        migrations.RemoveField(
            model_name='historicaldocumentounicofinanceiro',
            name='banco',
        ),
        migrations.RemoveField(
            model_name='historicaldocumentounicofinanceiro',
            name='cfop',
        ),
        migrations.RemoveField(
            model_name='historicaldocumentounicofinanceiro',
            name='chave',
        ),
        migrations.RemoveField(
            model_name='historicaldocumentounicofinanceiro',
            name='chave_pix',
        ),
        migrations.RemoveField(
            model_name='historicaldocumentounicofinanceiro',
            name='cnpj',
        ),
        migrations.RemoveField(
            model_name='historicaldocumentounicofinanceiro',
            name='conta',
        ),
        migrations.RemoveField(
            model_name='historicaldocumentounicofinanceiro',
            name='digito',
        ),
        migrations.RemoveField(
            model_name='historicaldocumentounicofinanceiro',
            name='linha_digitavel',
        ),
        migrations.RemoveField(
            model_name='historicaldocumentounicofinanceiro',
            name='mod',
        ),
        migrations.RemoveField(
            model_name='historicaldocumentounicofinanceiro',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='historicaldocumentounicofinanceiro',
            name='serie',
        ),
        migrations.RemoveField(
            model_name='historicaldocumentounicofinanceiro',
            name='tipo_anexo',
        ),
        migrations.AddField(
            model_name='contrato',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fornecedor_contrato', to='cadastro.pessoa'),
        ),
        migrations.AddField(
            model_name='documentounicofinanceiro',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documento_unico_contrato', to='janela_unica.contrato'),
        ),
        migrations.AddField(
            model_name='historicaldocumentounicofinanceiro',
            name='contrato',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='janela_unica.contrato'),
        ),
        migrations.AlterField(
            model_name='documentounicofinanceiro',
            name='situacao',
            field=django_fsm.FSMField(choices=[('Edição Responsável', 'Edição Responsável'), ('Aguardando avaliação', 'Aguardando avaliação'), ('Aguardando avaliação Gerência', 'Aguardando avaliação Gerência'), ('Aguardando avaliação Superintendencia', 'Aguardando avaliação Superintendencia'), ('Aguardando avaliação Diretoria', 'Aguardando avaliação Diretoria'), ('Aguardando Análise Fiscal', 'Aguardando Análise Fiscal'), ('Aguardando Análise Financeira', 'Aguardando Análise Financeira'), ('Reprovado', 'Reprovado'), ('Finalizado', 'Finalizado'), ('Cancelado', 'Cancelado'), ('Aprovado', 'Aprovado'), ('Devolvido', 'Devolvido')], default='Edição Responsável', max_length=50, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='historicaldocumentounicofinanceiro',
            name='situacao',
            field=django_fsm.FSMField(choices=[('Edição Responsável', 'Edição Responsável'), ('Aguardando avaliação', 'Aguardando avaliação'), ('Aguardando avaliação Gerência', 'Aguardando avaliação Gerência'), ('Aguardando avaliação Superintendencia', 'Aguardando avaliação Superintendencia'), ('Aguardando avaliação Diretoria', 'Aguardando avaliação Diretoria'), ('Aguardando Análise Fiscal', 'Aguardando Análise Fiscal'), ('Aguardando Análise Financeira', 'Aguardando Análise Financeira'), ('Reprovado', 'Reprovado'), ('Finalizado', 'Finalizado'), ('Cancelado', 'Cancelado'), ('Aprovado', 'Aprovado'), ('Devolvido', 'Devolvido')], default='Edição Responsável', max_length=50, verbose_name='Situação'),
        ),
        migrations.CreateModel(
            name='AvaliacaoDocumentoUnico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequencia', models.IntegerField(blank=True, null=True)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('observacao', models.CharField(blank=True, max_length=1055, null=True)),
                ('aprovado', models.BooleanField(blank=True, null=True)),
                ('documento_unico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documento_unico_avaliacao', to='janela_unica.documentounicofinanceiro')),
                ('usuario_avaliador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documento_unico_usuario_avaliador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avaliação para Pagamento',
                'verbose_name_plural': 'Avaliações para Pagamento',
            },
        ),
        migrations.CreateModel(
            name='ArquivoSolicitacaoContrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('obrigatorio', models.BooleanField(default=False)),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contrato_arquivo_solicitacao', to='janela_unica.contrato')),
            ],
            options={
                'verbose_name': 'Documento para fim de Pagamento',
                'verbose_name_plural': 'Documentos para fins de Pagamento',
            },
        ),
        migrations.CreateModel(
            name='AprovadorContrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequencia', models.IntegerField(blank=True, null=True)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('obrigatorio', models.BooleanField(default=False)),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contrato_aprovador_solicitacao', to='janela_unica.contrato')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aprovador_grupo_contrato', to='auth.group')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aprovador_usuario_contrato', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aprovador Solicitação',
                'verbose_name_plural': 'Avaliadores para fins de Pagamento',
            },
        ),
    ]
