# Generated by Django 3.2.10 on 2023-08-16 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('janela_unica', '0009_auto_20230726_1142'),
        ('janela_unica', '0010_contrato_tipocontrato'),
    ]

    operations = [
    ]
