# Generated by Django 3.2.10 on 2023-08-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janela_unica', '0012_auto_20230820_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentounicofinanceiro',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historicaldocumentounicofinanceiro',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='data_validade',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentounicofinanceiro',
            name='tipo_arquivo',
            field=models.CharField(blank=True, choices=[('8', 'Contrato'), ('0', 'Nota Fiscal (NF-e)'), ('1', 'DANFE'), ('2', 'Boleto'), ('3', 'Comprovante de Pagamento'), ('9', 'Outros')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcontrato',
            name='data_validade',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldocumentounicofinanceiro',
            name='tipo_arquivo',
            field=models.CharField(blank=True, choices=[('8', 'Contrato'), ('0', 'Nota Fiscal (NF-e)'), ('1', 'DANFE'), ('2', 'Boleto'), ('3', 'Comprovante de Pagamento'), ('9', 'Outros')], max_length=1, null=True),
        ),
    ]
