BBBBBBB BBBBBBBBBBBBBBBB

BBBBB BBBBBFFFFFBBBBBBBB
BBBBB BBBBBBB
XXXXXXXX XXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX
  
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
    
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBB

    XXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXX
        XXXXX XXXXXXXXX XXXXXXXXXXXXXX
          BBBBBBBBBB
          XXXX XXXXXXXXXXXXXXX
            XXXX
              
            XXXXX
              XXXX XXXXXXXXXXXXXXXXXXX
                XXXX XX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXX
                XXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX

                    XXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX


              XXXXXX
          XXXXXX

          XXXX XXXXXXXXXXXXX

           BBBBBBB BBBBBBBBBBBBBBBBBB

           XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
              XXXXXXX
                XXXX
                    XXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXX XX XXXXXXXXXXXXX
                    XXXXXXXX XXXXXXXXXXX
                    XXXXXXXX XXXXXXXX
                    XXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXX
                    XXXXXXXX XX XXXXXXXXXXX
                    XXXXXXXX XX XXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXX XX XXXXXXXXXXX

                  XXXXXXXXXXXXXXXXXXX
                XXXXX
              XXXXXXXX

              XXXXXXX
               BB BBBBBBBBBB
               BBB BBBBB BB BBBBBBBBBB

               XXX X
                   XXXXXXXXX
                   XXXXXXXXX
                   XXXXXX XXXXX
                   XXXXXXXXX
                   XXXXXXXXX
                   XXXXXXXXX
                   XXXXXXXXX
                   XXXXXXXXX
                   XXXXXXXXX
                   XXXXXXXXX
                   XXXXXXXXX
                   XXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX  XXXXXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBXXXXXXXX XXX XXXXXXXXXXX XXXXXXXXXXXXXXXX

                   XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBB  BBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXX XXXXXXXXX XX XXXXXX XXXXXXXXXXXXXXXX

                XXX XXXXXXXXXXXXXXXXXXXXX
                  XXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX
              XXXXX
              BBBBBB
              BBBB
              BBBBB
            XXXXXXXX
          XXXXXXXX
        XXXXXX

      XXXXXX

    XXXXXXX

  XXXXXX
XXXXXX

  

        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB

        

XXXXXX
XXXXXXXXXX


BBBBBBBB

BBBBB BB

  BBBB BBBBBB

  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXX

BBBBBBBB