BBBBBBB BBBBBBBBBBBBBBBB

BBBBB BBBBBFFFFFBBBBBBBB
BBBBB BBBBBBB
XXXXXXXX XXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX
  
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
    
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBB

    XXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXX
        XXXXX XXXXXXXXX XXXXXXXXXXXXXX
          BBBBBBBBBB
          XXXX XXXXXXXXXXXXXXX
            XXXX
              
            XXXXX
              XXXX XXXXXXXXXXXXXXXXXXX
                XX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
                XXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

              XXXXXX
          XXXXXX

          XXXX XXXXXXXXXXXXX

           BBBBBBB BBBBBBBBBBBBBBBBBB

           XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
              XXXXXXX
                XXXX
                  XXXXXXXXXXXXXXX
                  XXXXXXXXXXXXXXXXXX
                  XXXXXXXXXXXXXXXX
                XXXXX
              XXXXXXXX

              XXXXXXX
               BB BBBBBBBBBB
               BBB BBBBB BB BBBBBBBBBB

               XXX XXXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBXX
                    XXXXXXXXX
                    XXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXXXXXX
                  XXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX
              XXXXX
              BBBBBB
              BBBB
              BBBBB
            XXXXXXXX
          XXXXXXXX
        XXXXXX

      XXXXXX

    XXXXXXX

  XXXXXX
XXXXXX

XXXXXX
XXXXXXXXXX


BBBBBBBB