BBBBBBB BBBBBBBBBBBBBBBB

BBBBB BBBBBFFFFFBBBBBBBB
BBBBB BBBBBBB
XXXXXXXX XXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX
  
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
    
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBB

    XXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXX
        XXXXX XXXXXXXXX XXXXXXXXXXXXXX
          BBBBBBBBBB
          XXXX XXXXXXXXXXXXXXX
            XXXX
              
            XXXXX
              XXXX XXXXXXXXXXXXXXXXXXX
                XXXX XX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXX
                XXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX


                  XXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX

              XXXXXX
          XXXXXX

          XXXX XXXXXXXXXXXXX

           BBBBBBB BBBBBBBBBBBBBBBBBB

           XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
              XXXXXXX
                XXXX
                    XXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXX

                    XXXXXXXX XXXXXXXXXXX
                    XXXXXXXX XXXXXXXX
                    XXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXX

                    XXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXX
                  XXXXXXXXXXXXXXXXXXX
                XXXXX
              XXXXXXXX

              XXXXXXX
               BB BBBBBBBBBB
               BBB BBBBB BB BBBBBBBBBB

               XXX
                       XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX  XXXXXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBX

               X
                   XXXXXXXXX
                   XXXXXXXXX

                   XXXXXXXXX
                   XXXXBB BBBBBBBBBBBBBBBBBBXXXBBBBBXXXXX
                   XXXXXXXXX
                   XXXXXXXXX


                   XXXX
                        BB BBBBBBBBBBBBBBBBBBBB
                            XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                        BBBB
                            XX XXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                        BBBBB
                    XXXXX
                    XXXX
                        BB BBBBBBBBBBBBBBBBBBBB
                            XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                        BBBB
                            XX XXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                        BBBBB
                    XXXXX
                   XXXX
                        BB BBBBBBBBBBBBBBBB
                            XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                        BBBB
                            XX XXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                        BBBBB
                   XXXXX
                XXX XXXXXXXXXXXXXXXXXXXXX
                  XXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX
              XXXXX
              BBBBBB
              BBBB
              BBBBB
            XXXXXXXX
          XXXXXXXX
        XXXXXX

      XXXXXX

    XXXXXXX

  XXXXXX
XXXXXX

        

        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB

        

XXXXXX
XXXXXXXXXX


BBBBBBBB

BBBBB BB

  BBBB BBBBBB

  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXX

BBBBBBBB