# Generated by Django 3.2.10 on 2023-04-13 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('norli_projeto', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HorasSemanais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hr_seg', models.CharField(max_length=200)),
                ('hr_ter', models.CharField(max_length=200)),
                ('hr_qua', models.CharField(max_length=200)),
                ('hr_qui', models.CharField(max_length=200)),
                ('hr_sex', models.CharField(max_length=200)),
                ('hr_sab', models.CharField(max_length=200)),
                ('hr_dom', models.CharField(max_length=200)),
                ('semanas', models.CharField(choices=[('26/03/2023 - 01/04/2023', '26/03/2023 - 01/04/2023'), ('02/04/2023 - 08/04/2023', '02/04/2023 - 08/04/2023'), ('09/04/2023 - 15/04/2023', '09/04/2023 - 15/04/2023'), ('16/04/2023 - 22/04/2023', '16/04/2023 - 22/04/2023'), ('23/04/2023 - 29/04/2023', '23/04/2023 - 29/04/2023')], max_length=200)),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificados_user', to='norli_projeto.exemplomodel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timesheet_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
