# Generated by Django 3.2.10 on 2023-06-11 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('norli_projeto', '0002_auto_20230417_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorasSemanais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hr_seg', models.CharField(blank=True, max_length=200)),
                ('hr_ter', models.CharField(blank=True, max_length=200)),
                ('hr_qua', models.CharField(blank=True, max_length=200)),
                ('hr_qui', models.CharField(blank=True, max_length=200)),
                ('hr_sex', models.CharField(blank=True, max_length=200)),
                ('hr_sab', models.CharField(blank=True, max_length=200)),
                ('hr_dom', models.CharField(blank=True, max_length=200)),
                ('semanas', models.CharField(choices=[('28/05/2023 - 03/06/2023', '28/05/2023 - 03/06/2023'), ('04/06/2023 - 10/06/2023', '04/06/2023 - 10/06/2023'), ('11/06/2023 - 17/06/2023', '11/06/2023 - 17/06/2023'), ('18/06/2023 - 24/06/2023', '18/06/2023 - 24/06/2023'), ('25/06/2023 - 01/07/2023', '25/06/2023 - 01/07/2023')], max_length=200)),
                ('situacao', models.IntegerField(default=0)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados_user', to='norli_projeto.exemplomodel')),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timesheet_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=500)),
                ('valor', models.CharField(max_length=10)),
                ('file', models.FileField(upload_to='files/')),
                ('situacao', models.CharField(blank=True, choices=[('3', 'REPROVADA'), ('2', 'APROVADA'), ('1', 'SUBMETIDA'), ('0', 'NÃO SUBMETIDA')], default='0', max_length=1, null=True)),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projeto_gastos', to='norli_projeto.exemplomodel')),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gastos_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
