# Generated by Django 3.2.10 on 2023-08-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horassemanais',
            name='semanas',
            field=models.CharField(choices=[('30/07/2023 - 05/08/2023', '30/07/2023 - 05/08/2023'), ('06/08/2023 - 12/08/2023', '06/08/2023 - 12/08/2023'), ('13/08/2023 - 19/08/2023', '13/08/2023 - 19/08/2023'), ('20/08/2023 - 26/08/2023', '20/08/2023 - 26/08/2023'), ('27/08/2023 - 02/09/2023', '27/08/2023 - 02/09/2023')], max_length=200),
        ),
    ]
