# Generated by Django 3.2.10 on 2023-07-04 21:46

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('norli_projeto', '0003_alter_filialmodel_empresa'),
        ('timesheet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastos',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gastos',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='horassemanais',
            name='semanas',
            field=models.CharField(choices=[('25/06/2023 - 01/07/2023', '25/06/2023 - 01/07/2023'), ('02/07/2023 - 08/07/2023', '02/07/2023 - 08/07/2023'), ('09/07/2023 - 15/07/2023', '09/07/2023 - 15/07/2023'), ('16/07/2023 - 22/07/2023', '16/07/2023 - 22/07/2023'), ('23/07/2023 - 29/07/2023', '23/07/2023 - 29/07/2023'), ('30/07/2023 - 05/08/2023', '30/07/2023 - 05/08/2023')], max_length=200),
        ),
        migrations.CreateModel(
            name='PercentualDiario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('percentual', models.DecimalField(decimal_places=2, default=0.0, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('observacao', models.CharField(blank=True, max_length=500, null=True)),
                ('situacao', models.IntegerField(default=0)),
                ('motivo_reprovacao', models.CharField(blank=True, max_length=500, null=True)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projeto_timesheet', to='norli_projeto.exemplomodel')),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timesheet_diaria_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Timesheet - Percentual',
                'permissions': (('aprovar_horas', 'Pode aprovar lançamento de horas'),),
            },
        ),
    ]
