# Generated by Django 3.2.10 on 2023-08-10 01:09

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0002_alter_horassemanais_semanas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='percentualdiario',
            name='percentual',
            field=models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
    ]
