# Generated by Django 3.2.10 on 2023-07-20 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('norli_projeto', '0003_alter_filialmodel_empresa'),
        ('timesheet', '0003_auto_20230710_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastos',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projeto_gastos', to='norli_projeto.exemplomodel'),
        ),
        migrations.CreateModel(
            name='OpiniaoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('opiniao', models.CharField(max_length=500)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timesheet_opiniao_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Timesheet - Opiniões',
                'permissions': (('analisar_opinioes', 'Vizualiza todas as opiniões'),),
            },
        ),
    ]
