# Generated by Django 3.2.10 on 2023-04-22 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0003_auto_20230422_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horassemanais',
            old_name='user',
            new_name='solicitante',
        ),
    ]
