# Generated by Django 3.2.10 on 2023-04-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0004_rename_user_horassemanais_solicitante'),
    ]

    operations = [
        migrations.AddField(
            model_name='horassemanais',
            name='aprovada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='horassemanais',
            name='reprovada',
            field=models.BooleanField(default=False),
        ),
    ]
