# Generated by Django 3.2.10 on 2023-07-20 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('norli_projeto', '0003_alter_filialmodel_empresa'),
        ('timesheet', '0004_auto_20230720_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastos',
            name='projeto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projeto_gastos', to='norli_projeto.exemplomodel'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='OpiniaoModel',
        ),
    ]
