# Generated by Django 3.2.10 on 2023-05-04 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0005_auto_20230423_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horassemanais',
            name='semanas',
            field=models.CharField(choices=[('30/04/2023 - 06/05/2023', '30/04/2023 - 06/05/2023'), ('07/05/2023 - 13/05/2023', '07/05/2023 - 13/05/2023'), ('14/05/2023 - 20/05/2023', '14/05/2023 - 20/05/2023'), ('21/05/2023 - 27/05/2023', '21/05/2023 - 27/05/2023'), ('28/05/2023 - 03/06/2023', '28/05/2023 - 03/06/2023')], max_length=200),
        ),
    ]
