# Generated by Django 3.2.10 on 2023-07-12 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0002_auto_20230704_1846'),
        ('timesheet', '0007_percentualdiario_motivo_reprovacao'),
    ]

    operations = [
    ]
