# Generated by Django 3.2.10 on 2022-11-15 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_auto_20221115_1505'),
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='condicaopagamento',
            options={'verbose_name': 'Condição de Pagamento'},
        ),
        migrations.AlterModelOptions(
            name='orcamentovenda',
            options={'verbose_name': 'Orçamento de Venda'},
        ),
        migrations.AlterModelOptions(
            name='pedidovenda',
            options={'permissions': (('faturar_pedidovenda', 'Pode faturar Pedidos de Venda'),), 'verbose_name': 'Pedido de Venda'},
        ),
        migrations.AlterField(
            model_name='venda',
            name='local_orig',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='venda_local_estoque', to='estoque.localestoque'),
        ),
    ]
