# Generated by Django 3.2.10 on 2023-08-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_auto_20221115_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='codigo_legado',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
