# Generated by Django 3.2.10 on 2022-12-08 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0006_delete_exemplo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default=' ', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoEquipamentoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('descricao', models.CharField(default=' ', max_length=50)),
                ('ativo', models.CharField(blank=True, choices=[('SIM', 'SIM'), ('NÃO', 'NÃO')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default=' ', max_length=50)),
                ('numero', models.IntegerField()),
                ('conjunto_aneel', models.CharField(default=' ', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MedidorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MunicipioModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_municipio', models.CharField(max_length=50)),
                ('codigo_ibge', models.IntegerField()),
                ('conta_cosip', models.IntegerField()),
                ('conta_ativo', models.IntegerField()),
                ('provisao', models.IntegerField()),
                ('uf_nome', models.CharField(max_length=2)),
                ('uf_cod', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RegionalModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_regional', models.CharField(max_length=50)),
                ('funcionarios_proprios', models.IntegerField()),
                ('funcionarios_terceirizados', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ServicoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default=' ', max_length=50)),
                ('codigo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SubClasseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default=' ', max_length=50)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classe_sub_classe', to='zeppelin.classemodel')),
            ],
        ),
        migrations.CreateModel(
            name='SubGrupoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Sub-Grupo', max_length=50)),
                ('tensao_maxima', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tensao_minima', models.DecimalField(decimal_places=2, max_digits=5)),
                ('carga', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEspecialModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default=' ', max_length=50)),
                ('codigo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UnidadeConsumidoraModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('grupo', models.CharField(blank=True, choices=[('A', 'GRUPO A'), ('B', 'GRUPO B')], max_length=10, null=True)),
                ('modalidade_tarifaria', models.CharField(blank=True, choices=[('1', 'HORÁRIO VERDE'), ('2', 'HORÁRIO AZUL'), ('3', 'FORA DE PONTA'), ('4', 'CONVENCIONAL'), ('5', 'HORÁRIO BRANCO')], max_length=10, null=True)),
                ('tipo_fornecimento', models.CharField(blank=True, choices=[('MONOFÁSICO', 'MONOFÁSICO'), ('BIFÁSICO', 'BIFÁSICO'), ('TRIFÁSICO', 'TRIFÁSICO')], max_length=10, null=True)),
                ('tipo_contabilidade', models.CharField(blank=True, choices=[('NORMAL', 'NORMAL'), ('INDIVIDUAL', 'INDIVIDUAL')], max_length=10, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uc_cliente', to='cadastro.cliente')),
                ('medidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uc_sg', to='zeppelin.medidormodel')),
                ('sub_classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uc_classe', to='zeppelin.subclassemodel')),
                ('subgrupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uc_sg', to='zeppelin.subgrupomodel')),
                ('tipo_especial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uc_sg', to='zeppelin.tipoespecialmodel')),
            ],
        ),
        migrations.CreateModel(
            name='MotivoDesligamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sai_ficha_de_leitura', models.CharField(blank=True, choices=[('SIM', 'SIM'), ('NÃO', 'NÃO')], max_length=10, null=True)),
                ('exporta_carga_mensal', models.CharField(blank=True, choices=[('SIM', 'SIM'), ('NÃO', 'NÃO')], max_length=10, null=True)),
                ('gera_solicitacao_desligamento', models.CharField(blank=True, choices=[('SIM', 'SIM'), ('NÃO', 'NÃO')], max_length=10, null=True)),
                ('situacao', models.CharField(max_length=100)),
                ('crm', models.CharField(blank=True, choices=[('SIM', 'SIM'), ('NÃO', 'NÃO')], max_length=10, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('DEFINITIVO', 'DEFINITIVO'), ('PROGRAMADO', 'PROGRAMADO')], max_length=10, null=True)),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servico_motivo', to='zeppelin.servicomodel')),
            ],
        ),
        migrations.CreateModel(
            name='EquipamentoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('nome', models.CharField(default=' ', max_length=100)),
                ('potencia', models.FloatField()),
                ('hora_dia', models.IntegerField()),
                ('dia_mes', models.IntegerField()),
                ('classe', models.ManyToManyField(to='zeppelin.ClasseModel')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupo_equipamento', to='zeppelin.grupoequipamentomodel')),
            ],
        ),
    ]
