# Generated by Django 3.2.10 on 2022-12-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zeppelin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cnaeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('descricao', models.CharField(default=' ', max_length=50)),
                ('prioridade', models.IntegerField()),
                ('permite_rural', models.CharField(blank=True, choices=[('SIM', 'SIM'), ('NÃO', 'NÃO')], max_length=10, null=True)),
            ],
        ),
    ]
