# Generated by Django 3.2.10 on 2022-12-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zeppelin', '0003_historicopadraomodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoBoletimAfericaoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('nome', models.CharField(default=' ', max_length=100)),
                ('motivo', models.CharField(blank=True, choices=[('SIM', 'SIM'), ('NÃO', 'NÃO')], max_length=10, null=True)),
            ],
        ),
    ]
