# Generated by Django 3.2.10 on 2022-12-08 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zeppelin', '0004_tipoboletimafericaomodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoboletimafericaomodel',
            name='motivo',
            field=models.CharField(blank=True, choices=[('DEFICIÊNCIA DO MEDIDOR', 'DEFICIÊNCIA DO MEDIDOR'), ('OUTROS', 'OUTROS')], max_length=25, null=True),
        ),
    ]
