# Generated by Django 3.2.10 on 2022-12-08 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zeppelin', '0006_tipodocumentomodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoServicoEssencialModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('definicao', models.CharField(default=' ', max_length=100)),
                ('ativo', models.CharField(blank=True, choices=[('SIM', 'SIM'), ('NÃO', 'NÃO')], max_length=25, null=True)),
                ('descricao_completa', models.CharField(default=' ', max_length=100)),
                ('tipo', models.CharField(blank=True, choices=[('SERVIÇO PÚBLICO', 'SERVIÇO PÚBLICO'), ('EQUIPAMENTO VITAL', 'EQUIPAMENTO VITAL')], max_length=25, null=True)),
            ],
        ),
    ]
