# Generated by Django 3.2.10 on 2022-12-08 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zeppelin', '0007_tiposervicoessencialmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroDeFinalidadeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('nome', models.CharField(default=' ', max_length=100)),
                ('descricao', models.CharField(default=' ', max_length=100)),
            ],
        ),
    ]
