# Generated by Django 3.2.10 on 2022-12-08 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zeppelin', '0008_cadastrodefinalidademodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoReprovacaoVistoriaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('ativo', models.CharField(blank=True, choices=[('SIM', 'SIM'), ('NÃO', 'NÃO')], max_length=25, null=True)),
                ('descricao', models.CharField(default=' ', max_length=100)),
                ('motivo', models.CharField(default=' ', max_length=100)),
                ('finalidade_obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupo_equipamento', to='zeppelin.cadastrodefinalidademodel')),
            ],
        ),
    ]
