# Generated by Django 3.2.10 on 2023-01-10 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zeppelin', '0009_motivoreprovacaovistoriamodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriterioBaixaRendaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('descricao', models.CharField(default=' ', max_length=100)),
                ('tipo', models.CharField(default=' ', max_length=100)),
                ('ativo', models.CharField(blank=True, choices=[('SIM', 'SIM'), ('NÃO', 'NÃO')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MotivoCancelamentoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('descricao', models.CharField(default=' ', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MotivoDeferimentoBaixaRendaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('descricao', models.CharField(default=' ', max_length=100)),
                ('origem_solicitacao', models.CharField(default=' ', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MotivoReprovacaoAnaliseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('descricao', models.CharField(default=' ', max_length=100)),
                ('motivo_cancelamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reprovacao_cancelamento', to='zeppelin.motivocancelamentomodel')),
                ('motivo_reprovacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reprovacao_reprovacao', to='zeppelin.motivoreprovacaovistoriamodel')),
            ],
        ),
    ]
