BB BBBBBBBBBBB
BBB BBBBB BB BBBB
BBB BBBBB BB BBBBBBBBBBBB
XXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXX
  XXXXXXXXXXXXXXXX
  FFFFFF
XXXXXX
BBBBBB
BBBBBB
BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBB
XXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXX
  FFFFFF
XXXXXX
BBBBBB
BBBBB