BB BBBBBBBB
BBB BBBBBBB BB BBBBBBBB
BB BBBBBBBBB BB BBBBBBBBBBBB
XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  FFFF
XXXXXX
BBBBB
BBBBBB
BBBBB