BB BBBBBBBB
BBB BBBBBBB BB BBBBBBBB
BB BBBBBBB BB BBBBBBBBBBBB
XXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXFFFFXXXX
XXXXXX
BBBBB
BBBBBB
BBBBB