# Generated by Django 3.2.10 on 2023-06-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='data_inativacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='data_inclusao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='date_ultima_modificacao',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(blank=True, choices=[('0', 'Solicitante'), ('1', 'Diretor da Unidade Solicitante (DUS)'), ('2', 'Superintendente')], default='0', max_length=50, null=True),
        ),
    ]
