# Generated by Django 3.2.10 on 2023-06-14 12:13

from django.db import migrations, models
import django_cpf_cnpj.fields


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20230611_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='certificado_digital',
            field=models.CharField(blank=True, choices=[('0', 'NÃO'), ('1', 'SIM')], default='0', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cpf',
            field=django_cpf_cnpj.fields.CPFField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='grupo_funcional',
            field=models.CharField(blank=True, choices=[('0', 'A - DIRETORES e CONSELHEIROS'), ('1', 'B – PROFISSIONAIS')], default='0', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='matricula',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='pcd',
            field=models.CharField(blank=True, choices=[('0', 'NÃO'), ('1', 'SIM')], default='0', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
