# Generated by Django 3.2.10 on 2023-07-23 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0014_departamentomodel'),
        ('login', '0006_remove_usuario_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departamento_usuario', to='cadastro.departamentomodel'),
        ),
    ]
